/* Bahasa Malaysia for the hand-written questions and the step-back (I'm Confused) ladders.
   Keys: h = hints, s = worked steps, w = wrong-answer nudges (by option), c = check line,
   y = reasoning question { q, o }, cf = question-specific ladder { intro, steps: [{ t, o, h }] }.
   Merged into FMQ.questions / FMQ.ladders at load, as hintsBm, showBm, checkBm, etc. */
window.FMQ = window.FMQ || {};

FMQ.questionsBm = {
  'pv-1': { h: ['Digit 5 berada di tempat apa: sa, puluh, ratus atau ribu?', 'Kira tempat dari kanan: sa, puluh, ratus…', 'Digit 5 di tempat ratus. Berapakah 5 ratus?'], s: ['4 572 = 4 ribu, 5 ratus, 7 puluh, 2 sa.', '5 ratus = 500.'], w: { '5': 'Digitnya 5, tetapi tempatnya menjadikan nilainya lebih besar. Di tempat manakah ia?', '50': 'Kira tempat sekali lagi dari kanan.' } },
  'pv-2': { h: ['3 000 mengubah tempat apa: ratus atau ribu?', 'Hanya digit ribu yang berubah.', '25 406 ada 5 ribu. Tambah 3 ribu lagi.'], s: ['3 000 ialah 3 ribu.', '25 406 → digit ribu 5 menjadi 8.', '25 406 + 3 000 = 28 406.'], w: { '25 706': 'Anda mengubah tempat ratus. 3 000 mengubah tempat lain.', '55 406': 'Anda mengubah tempat puluh ribu. Semak tempat bagi 3 000.', '25 409': 'Anda mengubah tempat sa. 3 000 jauh lebih besar daripada 3.' } },
  'pv-3': { h: ['Tempat apa yang disebut? Ada tempat yang tiada?', 'Tulis satu digit bagi setiap tempat: ribu, ratus, puluh, sa.', 'Tiada puluh. Digit apa ditulis untuk sifar puluh?'], s: ['Ribu 2, ratus 4, puluh 0, sa 9.', 'Nombornya 2 409.'], w: { '249': 'Setiap tempat perlukan digit, walaupun sifar.', '2 490': 'Semak tempat puluh. Ada puluh yang disebut?' } },
  'pv-4': { h: ['Nombor manakah yang paling banyak digit?', 'Bandingkan 10 200 dan 10 020 digit demi digit dari kiri.', 'Kedua-duanya bermula dengan 10. Bandingkan digit ratus pula.'], s: ['10 200 dan 10 020 ada 5 digit, jadi lebih besar daripada nombor 4 digit.', 'Ratus: 2 lebih besar daripada 0, jadi 10 200 paling besar.'], w: { '9 999': '9 999 nampak besar, tetapi kira digit nombor yang lain.', '10 020': 'Bandingkan digit ratus bagi 10 020 dan 10 200.' } },
  'as-1': { h: ['Tambah sa dahulu.', '4 + 8 = 12. Apa kita buat dengan 1 puluh itu?', 'Bawa 1 ke lajur puluh: 5 + 3 + 1.'], s: ['Sa: 4 + 8 = 12 → tulis 2, bawa 1.', 'Puluh: 5 + 3 + 1 = 9.', 'Ratus: 2 + 1 = 3.', 'Jawapan: 392.'], w: { '316': 'Ini soalan tambah. Lihat tanda.', '382': 'Semak nilai yang dibawa dari lajur sa.', '492': 'Semak lajur ratus.' } },
  'as-2': { h: ['Apakah maksud “beza” bagi dua nombor?', 'Untuk membandingkan dua nombor, kita cari jaraknya. Operasi apa membantu?', 'Mula di 80 dan tolak 35. Tolak 30 dahulu.'], s: ['Beza bermaksud tolak nombor kecil daripada nombor besar.', '80 − 35 = 45.'], w: { '35': 'Itu salah satu nombor dalam soalan. Bandingkan 80 dan 35.', '55': 'Semak tolakan: 80 − 30 dahulu, kemudian − 5.', '115': 'Anda menambah. “Beza” membandingkan dua nombor.' }, c: 'Semak: 35 + 45 = 80 ✓', y: { q: 'Bagaimana anda tahu perlu tolak?', o: ['“Beza” bermaksud membandingkan dua nombor', 'Kerana 80 nombor genap', 'Ada dua nombor, jadi sentiasa tolak'] } },
  'as-3': { h: ['Kita mencari jumlah, atau membandingkan dua nilai?', '“Berapa banyak lagi” membandingkan dua nilai. Operasi apa?', 'Kira 125 − 60. Tolak 6 puluh daripada 12 puluh.'], s: ['“Berapa banyak lagi” bermaksud cari beza.', '125 − 60 = 65.', 'Hakim ada 65 pelekat lebih.'], w: { '185': 'Anda mencari jumlah. Soalan ini membandingkan dua nilai.' }, c: 'Semak: 60 + 65 = 125 ✓' },
  'as-4': { h: ['Apa berlaku kepada kuih yang dijual?', 'Ada kuih yang sudah tiada. Nombornya bertambah atau berkurang?', 'Tulis 1 250 dan letak 875 di bawahnya. Mula dengan sa: 0 − 5 perlu kumpul semula.'], s: ['Baki bermaksud yang masih ada.', '1 250 − 875 = 375.', '375 biji kuih masih ada.'], w: { '385': 'Semak lajur puluh.', '475': 'Semak kumpul semula di lajur ratus.', '2 125': 'Anda menambah. Kuih yang dijual sudah tiada.' }, c: 'Semak: 875 + 375 = 1 250 ✓' },
  'as-5': { h: ['Kita menggabungkan kelas atau membandingkannya?', '“Jumlah keseluruhan” bermaksud gabung. Operasi apa?', '32 + 29: tambah 30 dahulu, kemudian tolak 1.'], s: ['Jumlah keseluruhan bermaksud tambah.', '32 + 29 = 61.'], w: { '3': 'Anda mencari beza. “Jumlah keseluruhan” menggabungkan kumpulan.', '51': 'Semak puluh: 3 puluh + 2 puluh + 1 puluh yang dibawa.' } },
  'td-1': { h: ['6 × 7 bermaksud 6 kumpulan 7.', 'Tahu 6 × 6? Tambah satu lagi 6.', '6 × 6 = 36. Sekarang tambah 6.'], s: ['6 × 6 = 36.', '36 + 6 = 42.'], w: { '13': 'Anda menambah. × bermaksud kumpulan.', '36': 'Itu 6 × 6. Kita perlukan satu kumpulan lagi.', '48': 'Itu 6 × 8. Cuba kurang satu kumpulan.' } },
  'td-2': { h: ['Apa berlaku kepada gula-gula itu? Digabung atau dikongsi?', 'Bahagi sama rata ke dalam kumpulan menggunakan bahagi.', 'Cari 48 ÷ 6. Nombor apa darab 6 jadi 48?'], s: ['Dikongsi sama rata bermaksud bahagi.', '48 ÷ 6 = 8, kerana 6 × 8 = 48.', 'Setiap kanak-kanak dapat 8 biji gula-gula.'], w: { '7': 'Semak: 6 × 7 = 42, bukan 48.', '42': 'Anda menolak. Bahagi sama rata menggunakan operasi lain.' }, c: 'Semak: 6 × 8 = 48 ✓', y: { q: 'Kenapa anda bahagi?', o: ['Gula-gula dibahagi kepada kumpulan sama banyak', 'Kerana 48 lebih besar daripada 6', 'Bahagi sentiasa digunakan untuk gula-gula'] } },
  'td-3': { h: ['Setiap kotak ada bilangan pensel yang sama. Berapa kotak?', 'Kumpulan sama banyak digabung: operasi apa?', '24 × 5: kira 20 × 5 dan 4 × 5, kemudian tambah.'], s: ['5 kotak, setiap satu 24 → 24 × 5.', '20 × 5 = 100, 4 × 5 = 20.', '100 + 20 = 120 batang pensel.'], w: { '29': 'Anda menambah 24 dan 5. Ada 5 kumpulan 24.', '100': 'Anda kira 20 × 5. Jangan lupa 4 × 5.' } },
  'td-4': { h: ['Berapa kali 4 dalam 156?', 'Pecahkan 156 kepada 120 dan 36. Kedua-duanya mudah dibahagi dengan 4.', '120 ÷ 4 = 30. Sekarang cari 36 ÷ 4.'], s: ['156 = 120 + 36.', '120 ÷ 4 = 30, 36 ÷ 4 = 9.', '30 + 9 = 39.'], w: { '152': 'Anda menolak 4. ÷ bermaksud bahagi kepada kumpulan.' }, c: 'Semak: 39 × 4 = 156 ✓' },
  'td-5': { h: ['Kita tahu jumlah telur dan berapa muat dalam satu dulang. Apa yang kita cari?', 'Membahagi jumlah kepada kumpulan sama banyak menggunakan bahagi.', 'Cari 63 ÷ 9. Nombor apa darab 9 jadi 63?'], s: ['63 ÷ 9 = 7, kerana 9 × 7 = 63.', 'Dia memenuhkan 7 dulang.'], w: { '54': 'Anda tolak 9 sekali sahaja. Teruskan buat kumpulan 9.', '72': 'Anda menambah. Telur sedang dibahagikan ke dalam dulang.' } },
  'dec-1': { h: ['Susun titik perpuluhan dalam satu lajur dahulu.', 'Tolak persepuluh, kemudian sa.', 'Persepuluh: 6 − 3. Sa: 5 − 2.'], s: ['5.6 − 2.3', 'Persepuluh: 6 − 3 = 3. Sa: 5 − 2 = 3.', 'Jawapan: 3.3.'], w: { '7.9': 'Anda menambah. Lihat tanda.', '3.03': 'Kekalkan digit di tempat yang sama seperti dalam soalan.' } },
  'dec-2': { h: ['Berapa tempat perpuluhan bagi setiap nombor?', 'Tulis 7.2 sebagai 7.20 supaya kedua-dua nombor ada dua tempat perpuluhan.', 'Susun titik: 7.20 − 3.45. Mula dari perseratus: 0 − 5 perlu kumpul semula.'], s: ['7.2 = 7.20.', '7.20 − 3.45: kumpul semula, kemudian tolak setiap lajur.', 'Jawapan: 3.75.'], w: { '4.27': 'Titik perpuluhan tidak disusun. Tulis 7.2 sebagai 7.20 dahulu.', '4.85': 'Dalam setiap lajur, tolak digit bawah daripada digit atas. Mungkin perlu kumpul semula.', '3.85': 'Semak persepuluh selepas kumpul semula.' }, c: 'Semak: 3.75 + 3.45 = 7.20 ✓',
    cf: { intro: 'Mari susun titik perpuluhan dahulu.', steps: [{ t: 'Yang manakah sama dengan 7.2?', h: 'Menambah sifar di hujung nombor perpuluhan tidak mengubah nilainya.' }, { t: 'Berapakah 7.20 − 3.00?', h: 'Hanya sa yang berubah: 7 − 3.' }, { t: 'Berapakah 0.50 − 0.45?', h: '50 perseratus tolak 45 perseratus.' }] } },
  'dec-3': { h: ['Selepas dipotong, reben lebih panjang atau lebih pendek?', 'Lebih pendek bermaksud tolak. Beri kedua-dua nombor dua tempat perpuluhan.', 'Tulis 4.50 − 1.75 dengan titik disusun.'], s: ['4.5 m = 4.50 m.', '4.50 − 1.75 = 2.75.', 'Reben itu sekarang 2.75 m.'], w: { '6.25 m': 'Anda menambah. Memotong menjadikan reben lebih pendek.', '3.25 m': 'Susun titik perpuluhan: tulis 4.5 sebagai 4.50.' }, c: 'Semak: 2.75 + 1.75 = 4.50 ✓' },
  'dec-4': { h: ['7/10 bermaksud 7 persepuluh.', 'Persepuluh ialah tempat pertama selepas titik perpuluhan.', 'Tulis 0, kemudian titik, kemudian 7 di tempat persepuluh.'], s: ['7/10 = 7 persepuluh = 0.7.'], w: { '0.07': '0.07 ialah 7 perseratus. Kita perlukan persepuluh.', '7.10': 'Garis pecahan bukan titik perpuluhan.' } },
  'dec-5': { h: ['Tulis 10 sebagai nombor perpuluhan dengan satu tempat perpuluhan.', '10 = 10.0. Sekarang susun titik.', '10.0 − 6.4: kumpul semula satu sa menjadi 10 persepuluh.'], s: ['10.0 − 6.4', 'Kumpul semula: 9 sa dan 10 persepuluh.', '10 persepuluh − 4 persepuluh = 6 persepuluh; 9 − 6 = 3.', 'Jawapan: 3.6.'], w: { '4.6': 'Semak kumpul semula di lajur sa.', '16.4': 'Anda menambah. Lihat tanda.', '4.4': 'Tulis 10 sebagai 10.0 sebelum menolak.' }, c: 'Semak: 3.6 + 6.4 = 10 ✓' },
  'mon-1': { h: ['Apa yang kita cari?', 'Aina ada wang, kemudian berbelanja. Wangnya bertambah atau berkurang?', 'Tulis RM30.00 dan letak RM12.50 di bawahnya. Pastikan titik perpuluhan sebaris.'], s: ['Berbelanja mengurangkan wang, jadi tolak.', 'RM30.00 − RM12.50', 'Susun titik dan kumpul semula.', 'RM30.00 − RM12.50 = RM17.50.'], w: { 'RM42.50': 'Anda menambah. Apabila Aina berbelanja, wangnya bertambah atau berkurang?', 'RM18.50': 'Semak lajur sa selepas kumpul semula.', 'RM22.50': 'Semak lajur puluh.' }, c: 'Semak: RM17.50 + RM12.50 = RM30.00 ✓', y: { q: 'Bagaimana anda tahu perlu tolak?', o: ['Berbelanja mengurangkan wang', 'Nombornya ada titik perpuluhan', 'Soalan wang sentiasa tolak'] } },
  'mon-2': { h: ['Kita menggabungkan harga atau membandingkannya?', '“Jumlah” bermaksud tambah.', 'Tambah sen dahulu: 50 sen + 20 sen.'], s: ['Jumlah bermaksud tambah.', 'RM2.50 + RM1.20 = RM3.70.'], w: { 'RM1.30': 'Anda mencari beza. “Jumlah” menggabungkan harga.', 'RM37.00': 'Susun titik perpuluhan sebaris.' } },
  'mon-3': { h: ['Apakah “baki wang” di kedai?', 'Baki wang ialah wang yang tinggal daripada wang yang dibayar. Operasi apa?', 'Tulis RM20.00 − RM13.60 dengan titik perpuluhan sebaris.'], s: ['Baki wang = wang dibayar − harga.', 'RM20.00 − RM13.60 = RM6.40.'], w: { 'RM33.60': 'Anda menambah. Baki wang ialah wang yang dipulangkan selepas membayar.', 'RM7.40': 'Semak sa selepas kumpul semula.', 'RM6.60': 'Semak sen: 100 − 60.' }, c: 'Semak: RM13.60 + RM6.40 = RM20.00 ✓' },
  'mon-4': { h: ['Berapa bungkus, dan berapa harga sebungkus?', '3 bungkus dengan harga sama: boleh darab atau tambah 3 kali.', 'RM4.50 × 3: kira RM4 × 3 dan 50 sen × 3.'], s: ['RM4 × 3 = RM12.', '50 sen × 3 = RM1.50.', 'RM12 + RM1.50 = RM13.50.'], w: { 'RM7.50': 'Anda tambah 3 sekali sahaja. Ibu membeli 3 bungkus berharga RM4.50 sebungkus.', 'RM13.00': 'Semak bahagian sen: 50 sen × 3.' }, y: { q: 'Kenapa boleh darab di sini?', o: ['Setiap bungkus sama harga, jadi ia 3 kumpulan sama', 'Kerana 4.50 ada titik perpuluhan', 'Darab sentiasa memberi jawapan betul'] } },
  'mon-5': { h: ['Apa berlaku kepada wang Farah apabila dia membeli minuman?', 'Wang yang tinggal berkurang, jadi tolak.', 'RM15.00 − RM2.80: tolak RM3, kemudian tambah balik 20 sen.'], s: ['RM15.00 − RM2.80', 'RM15.00 − RM3.00 = RM12.00, kemudian + 20 sen.', 'Baki RM12.20.'], w: { 'RM17.80': 'Anda menambah. Membeli menggunakan wang.', 'RM12.80': 'Semak sen: 100 − 80.', 'RM13.20': 'Semak ringgit selepas kumpul semula.' }, c: 'Semak: RM12.20 + RM2.80 = RM15.00 ✓' },
  'fr-1': { h: ['Ada berapa bahagian yang sama besar?', 'Nombor bawah = semua bahagian. Nombor atas = bahagian berlorek.', 'Kira bahagian berlorek. Itu nombor atas.'], s: ['4 bahagian sama besar → nombor bawah 4.', '1 bahagian berlorek → nombor atas 1.', 'Pecahan: 1/4.'], w: { '1/3': 'Nombor bawah mengira semua bahagian, bukan bahagian yang tidak berlorek sahaja.', '4/1': 'Nombor manakah di atas: bahagian berlorek atau semua bahagian?', '3/4': 'Itu bahagian yang tidak berlorek.' } },
  'fr-2': { h: ['Apakah maksud 4 dalam 3/4 bagi 20?', 'Cari 1/4 daripada 20 dahulu: bahagi 20 kepada 4 kumpulan sama.', '1/4 daripada 20 ialah satu kumpulan. 3/4 ialah tiga kumpulan.'], s: ['20 ÷ 4 = 5, jadi 1/4 daripada 20 = 5.', '3/4 ialah 3 kumpulan: 3 × 5 = 15.'], w: { '5': 'Itu 1/4 daripada 20. Kita perlukan 3 bahagian.', '12': 'Semak 20 ÷ 4 dahulu.', '60': 'Anda darab 20 dengan 3. Bahagi 20 kepada 4 kumpulan dahulu.' }, c: 'Semak: 15 kurang daripada 20, sesuai untuk 3/4 ✓',
    cf: { intro: 'Sebelum menjawab, mari lihat suku.', steps: [{ t: 'Jika sesuatu dibahagi kepada 4 bahagian sama besar, apakah maksud 1/4?', o: ['1 daripada 4 bahagian sama besar', '4 benda penuh', '1 bahagian daripada 2'], h: 'Lihat bar. Satu bahagian berlorek daripada 4 bahagian sama besar.' }, { t: '20 biji gula-gula dibahagi kepada 4 kumpulan sama.\nBerapa biji dalam 1 kumpulan?', h: 'Kira titik dalam satu kumpulan.' }, { t: 'Jadi 1/4 daripada 20 ialah 5.\nBerapakah 2/4 daripada 20?', h: '2 kumpulan 5.' }] } },
  'fr-3': { h: ['Apakah maksud 3 dalam 2/3?', 'Bahagi 12 kepada 3 kumpulan sama dahulu.', '1/3 daripada 12 ialah satu kumpulan. Berapa kumpulan kita perlukan?'], s: ['12 ÷ 3 = 4, jadi 1/3 daripada 12 = 4.', '2/3 = 2 kumpulan: 2 × 4 = 8.'], w: { '4': 'Itu 1/3. Kita perlukan 2 kumpulan.', '6': 'Itu separuh daripada 12. Lihat pecahan sekali lagi.' }, c: 'Semak: 8 kurang daripada 12 ✓' },
  'fr-4': { h: ['Separuh bermaksud satu daripada dua bahagian sama besar.', 'Jika bar ada 4 bahagian, berapa perlu dilorek untuk nilai yang sama?', 'Bahagi setiap separuh kepada 2. Kira suku yang berlorek.'], s: ['Potong setiap separuh kepada 2 → 4 bahagian.', '2 daripada 4 bahagian berlorek.', '1/2 = 2/4.'], w: { '1/4': '1/4 lebih kecil daripada separuh.', '3/4': '3/4 lebih besar daripada separuh.' } },
  'fr-5': { h: ['1/5 bermaksud satu daripada 5 bahagian sama.', 'Bahagi 30 kepada 5 kumpulan sama.', 'Berapa kali 5 dalam 30?'], s: ['30 ÷ 5 = 6.', '1/5 daripada 30 = 6.'], w: { '25': 'Anda tolak 5. Bahagi 30 kepada 5 kumpulan.', '150': 'Anda mendarab. Pecahan daripada sesuatu nilai lebih kecil daripada nilai itu.' } },
  'pc-1': { h: ['Peratus bermaksud “daripada 100”.', 'Pecahan ini sudah ada 100 di bawah.', 'Nombor atas menjadi peratus.'], s: ['50/100 bermaksud 50 daripada 100.', '50 daripada 100 = 50%.'], w: { '5%': 'Daripada 100, nombor atas menunjukkan peratusnya.' } },
  'pc-2': { h: ['Peratus bermaksud daripada 100. Apa nombor bawah sekarang?', 'Tukar 10 kepada 100. Darab dengan berapa?', 'Darab nombor atas dan bawah dengan 10.'], s: ['7/10 = 70/100 (darab atas dan bawah dengan 10).', '70/100 = 70%.'], w: { '7%': '7% ialah 7 daripada 100. Pecahan kita daripada 10.', '17%': 'Jangan tambah nombor. Jadikan nombor bawah 100.', '710%': 'Peratus bermaksud daripada 100. Jadikan nombor bawah 100.' },
    cf: { intro: 'Mari mula dengan “daripada 100”.', steps: [{ t: 'Peratus bermaksud…', o: ['daripada 100', 'daripada 10', 'darab 100'], h: '“Per-ratus”: setiap seratus.' }, { t: '3/10 = ?/100', h: '10 × 10 = 100, jadi 3 × 10 di atas.' }, { t: '30/100 = ?%', h: 'Daripada 100, nombor atas ialah peratusnya.' }] } },
  'pc-3': { h: ['Tulis bunga merah sebagai pecahan dahulu.', '6 daripada 10 = 6/10. Sekarang jadikan nombor bawah 100.', 'Darab atas dan bawah 6/10 dengan 10.'], s: ['6 daripada 10 = 6/10.', '6/10 = 60/100 = 60%.'], w: { '6%': 'Ada 10 kuntum bunga, bukan 100. Tukar kepada “daripada 100”.', '40%': 'Itu bunga yang bukan merah.' }, c: 'Semak: lebih separuh merah, dan 60% lebih daripada 50% ✓' },
  'pc-4': { h: ['4 didarab dengan berapa untuk jadi 100?', '4 × 25 = 100. Buat yang sama pada nombor atas.', '1 × 25 = ?'], s: ['1/4 = 25/100.', '25/100 = 25%.'], w: { '14%': 'Jangan tulis digit bersebelahan. Jadikan nombor bawah 100.', '4%': 'Tukar nombor bawah kepada 100 dahulu.' } },
  'pc-5': { h: ['Kita cari kepingan yang dimakan atau yang tinggal?', 'Berapa kepingan tinggal daripada 10?', '7 daripada 10 tinggal. Tukar 7/10 kepada peratus.'], s: ['10 − 3 = 7 keping tinggal.', '7/10 = 70/100 = 70%.'], w: { '30%': 'Itu bahagian yang Amin makan. Soalan bertanya bahagian yang tinggal.', '7%': 'Tukar 7/10 kepada “daripada 100” dahulu.' }, c: 'Semak: 70% + 30% = 100% ✓' },
  't24-1': { h: ['Waktu p.m. ialah selepas jam 12 tengah hari.', 'Untuk waktu p.m., tambah 12 pada jam.', '3 + 12 = ?'], s: ['3:00 p.m. ialah waktu petang.', '3 + 12 = 15.', '3:00 p.m. = jam 1500.'], w: { '0300 hours': 'Jam 0300 ialah pukul 3 awal pagi. p.m. ialah selepas tengah hari.', '1300 hours': 'Jam 1300 ialah 1:00 p.m. Tambah 12 pada 3.' } },
  't24-2': { h: ['Adakah jam 1845 sebelum atau selepas jam 12 tengah hari?', 'Selepas tengah hari, tolak 12 daripada jam.', '18 − 12 = ? Minit 45 kekal.'], s: ['18 lebih daripada 12, jadi p.m.', '18 − 12 = 6.', 'Jam 1845 = 6:45 p.m.'], w: { '8:45 p.m.': 'Kita tolak 12, bukan 10.', '6:45 a.m.': '18 ialah selepas tengah hari, jadi p.m.', '4:45 p.m.': 'Semak 18 − 12.' },
    cf: { intro: 'Mari lihat cara sistem 24 jam berfungsi.', steps: [{ t: 'Jam 12 tengah hari dalam sistem 24 jam ialah…', h: 'Tengah hari ialah pertengahan hari: 12.' }, { t: '1 jam selepas tengah hari ialah 1:00 p.m.\nDalam sistem 24 jam ialah…', h: 'Teruskan mengira selepas 12: 13.' }, { t: 'Jadi jam 1600 ialah…', h: '16 − 12 = 4, dan ia selepas tengah hari.' }] } },
  't24-3': { h: ['Adakah 9:30 p.m. waktu pagi atau malam?', 'Untuk waktu p.m., tambah 12 pada jam.', '9 + 12 = ? Minit 30 kekal.'], s: ['9:30 p.m. ialah waktu malam.', '9 + 12 = 21.', '9:30 p.m. = jam 2130.'], w: { '0930 hours': 'Jam 0930 ialah waktu pagi.', '1930 hours': 'Tambah 12, bukan 10.' } },
  't24-4': { h: ['Waktu petang bermula selepas jam 12 tengah hari.', 'Waktu manakah jamnya lebih besar daripada 12?', 'Lihat dua digit pertama setiap waktu.'], s: ['Waktu petang ialah jam selepas 12.', 'Jam 1400 = 2:00 p.m.'], w: { '1100 hours': '11 ialah sebelum jam 12 tengah hari.' } },
  'du-1': { h: ['Fikir tentang jam. Berapa minit jarum panjang membuat satu pusingan penuh?', 'Setengah jam ialah 30 minit.', 'Gandakan 30.'], s: ['1 jam = 60 minit.'], w: { '24': '24 ialah bilangan jam dalam sehari.', '100': 'Masa tidak dikira dalam ratus. Fikir tentang jam.' } },
  'du-2': { h: ['Tempoh masa ialah masa dari mula hingga tamat.', 'Kira dari 2:15 p.m. hingga 3:15 p.m. dahulu.', '2:15 hingga 3:15 ialah 1 jam. Berapa minit dari 3:15 hingga 4:00?'], s: ['2:15 → 3:15 = 1 jam.', '3:15 → 4:00 = 45 minit.', 'Tempoh masa = 1 jam 45 minit.'], w: { '6 hours 15 minutes': 'Anda menambah waktu. Tempoh masa dikira dari mula hingga tamat.', '2 hours 15 minutes': 'Kira dari 2:15. Adakah 4:00 lebih daripada 2 jam kemudian?', '1 hour 15 minutes': '1 jam ada 60 minit, bukan 100. Kira minit dari 3:15 hingga 4:00.' }, c: 'Semak: 2:15 + 1 jam 45 minit = 4:00 ✓',
    cf: { intro: 'Mari kira masa dalam lompatan kecil.', steps: [{ t: 'Dari 2:00 p.m. hingga 3:00 p.m. ialah…', h: 'Nombor jam naik satu.' }, { t: 'Dari 3:30 p.m. hingga 4:00 p.m. ialah…', h: 'Setengah jam.' }, { t: 'Jadi 2:00 p.m. → 3:00 p.m. → 3:30 p.m. ialah…', h: 'Tambah lompatan: 1 jam, kemudian 30 minit.' }] } },
  'du-3': { h: ['Kita cari tempoh masa atau waktu tamat?', 'Tambah tempoh pada waktu mula.', 'Tambah 1 jam dahulu: 1430 → 1530. Kemudian tambah 20 minit.'], s: ['1430 + 1 jam = 1530.', '1530 + 20 minit = 1550.', 'Kelas tuisyen tamat pada jam 1550.'], w: { '1450 hours': 'Anda menambah minit. Sudah tambah jam juga?', '1530 hours': 'Anda menambah jam. Sekarang tambah 20 minit.' }, c: 'Semak: 1550 selepas 1430 ✓' },
  'du-4': { h: ['Berapa minit dalam 1 jam?', '2 jam = 2 × 60 minit.', '120 minit + 10 minit = ?'], s: ['2 jam = 120 minit.', '120 + 10 = 130 minit.'], w: { '210 minutes': '1 jam ialah 60 minit, bukan 100.', '120 minutes': 'Jangan lupa 10 minit lagi.' } },
  'du-5': { h: ['Kita perlukan masa antara dua waktu.', 'Kira dari 0845 hingga 0900 dahulu.', '0845 → 0900 ialah 15 minit. Kemudian 0900 → 0930?'], s: ['0845 → 0900 = 15 minit.', '0900 → 0930 = 30 minit.', '15 + 30 = 45 minit.'], w: { '85 minutes': 'Anda menolak seperti nombor biasa. 1 jam ada 60 minit, jadi kira ke depan.' }, c: 'Semak: 0845 + 45 minit = 0930 ✓' },
  'me-1': { h: ['Fikir tentang pembaris 1 meter.', '“Senti” bermaksud perseratus.', '1 m = ? cm'], s: ['1 m = 100 cm.'], w: { '10': '1 cm = 10 mm. Fikir tentang pembaris 1 meter.', '1 000': '1 000 untuk kilo (1 km = 1 000 m).' } },
  'me-2': { h: ['Adakah unitnya sama? Liter dan mililiter.', 'Tukar 1 liter kepada mililiter dahulu.', '1 liter = 1 000 ml. Sekarang tolak 350 ml.'], s: ['1 l = 1 000 ml.', '1 000 ml − 350 ml = 650 ml.'], w: { '1 350 ml': 'Anda menambah. Menuang keluar mengurangkan air.', '750 ml': 'Semak 1 000 − 350.', '350 ml': 'Itu air yang dituang keluar, bukan yang tinggal.' }, c: 'Semak: 650 ml + 350 ml = 1 000 ml ✓' },
  'me-3': { h: ['Adakah kg dan g unit yang sama?', 'Tukar 2 kg kepada gram.', '2 kg = 2 000 g. Tolak 500 g.'], s: ['2 kg = 2 000 g.', '2 000 g − 500 g = 1 500 g.'], w: { '2 500 g': 'Anda menambah. Ibu menggunakan sebahagian beras.', '1 050 g': 'Tukar 2 kg kepada gram dahulu: 1 kg = 1 000 g.' } },
  'me-4': { h: ['Berapa gram dalam 1 kg?', '1 kg = 1 000 g.', '3 × 1 000 = ?'], s: ['1 kg = 1 000 g.', '3 kg = 3 000 g.'], w: { '300 g': '1 kg ialah 1 000 g, bukan 100 g.' } },
  'pe-1': { h: ['Segi empat sama ada berapa sisi?', 'Perimeter ialah jumlah semua sisi di sekeliling bentuk.', '5 + 5 + 5 + 5 = ?'], s: ['Segi empat sama ada 4 sisi sama panjang.', '5 + 5 + 5 + 5 = 20 cm.'], w: { '25 cm': '5 × 5 ialah luas. Perimeter ialah jarak di sekeliling tepi.', '10 cm': 'Segi empat sama ada 4 sisi, bukan 2.' } },
  'pe-2': { h: ['Perimeter ialah jarak mengelilingi bentuk. Ada berapa sisi?', 'Segi empat tepat ada 2 sisi panjang dan 2 sisi pendek.', '8 + 3 + 8 + 3 = ?'], s: ['Sisi: 8, 3, 8, 3.', '8 + 3 + 8 + 3 = 22 cm.'], w: { '24 cm': '8 × 3 ialah luas. Perimeter ialah jumlah semua sisi.', '11 cm': 'Itu 2 sisi sahaja. Segi empat tepat ada 4 sisi.' }, y: { q: 'Kenapa anda tambah keempat-empat sisi?', o: ['Perimeter ialah jarak penuh di sekeliling tepi', 'Kerana tambah lebih mudah', 'Kerana bentuknya panjang'] } },
  'pe-3': { h: ['Pagar dipasang di sekeliling tepi atau menutup bahagian dalam?', 'Di sekeliling tepi bermaksud perimeter.', '10 + 6 + 10 + 6 = ?'], s: ['Pagar di sekeliling → perimeter.', '10 + 6 + 10 + 6 = 32 m.'], w: { '60 m': 'Anda mencari luas. Pagar dipasang di sekeliling tepi.', '16 m': 'Itu dua sisi. Kira semua sisi.' }, c: 'Semak: jawapan dalam meter (m), iaitu panjang ✓' },
  'pe-4': { h: ['Segi empat sama ada 4 sisi sama panjang.', '4 sisi sama panjang = 36 cm. Operasi apa untuk cari satu sisi?', '36 ÷ 4 = ?'], s: ['4 sisi sama panjang = 36 cm.', '36 ÷ 4 = 9 cm.'], w: { '6 cm': '6 × 6 = 36 ialah untuk luas. Segi empat sama ada 4 sisi.', '18 cm': 'Segi empat sama ada 4 sisi, bukan 2.' }, c: 'Semak: 9 + 9 + 9 + 9 = 36 ✓' },
  'ar-1': { h: ['Luas ialah ruang di dalam. Apa yang boleh dikira?', 'Kira petak berlorek. Cuba kira mengikut baris.', '3 baris, setiap baris 4 petak.'], s: ['3 baris × 4 petak = 12 petak.', 'Luas = 12 cm².'], w: { '14 cm²': 'Anda mengira di sekeliling tepi. Luas mengira petak di dalam.', '7 cm²': 'Anda menambah 4 + 3. Kira semua petak.' } },
  'ar-2': { h: ['Luas ialah ruang di dalam segi empat tepat.', 'Luas segi empat tepat = panjang × lebar.', '6 × 4 = ? Semak unitnya juga.'], s: ['Luas = panjang × lebar.', '6 × 4 = 24.', 'Luas = 24 cm² (sentimeter persegi).'], w: { '20 cm²': '20 ialah perimeter. Luas ialah ruang di dalam.', '24 cm': 'Nombornya betul. Luas menggunakan unit persegi.', '10 cm²': 'Anda menambah. Luas = panjang × lebar.' } },
  'ar-3': { h: ['Luas lantai ialah tepi atau ruang di dalam?', 'Panjang × lebar.', '9 × 7 = ?'], s: ['Luas = 9 × 7 = 63.', 'Luas = 63 m².'], w: { '32 m²': '32 ialah perimeter. Luas ialah ruang di dalam.', '56 m²': 'Itu 8 × 7. Semak 9 × 7.' } },
  'ar-4': { h: ['Menutup lantai berkaitan dengan tepi atau ruang di dalam?', 'Ruang di dalam ialah luas. Bagaimana mencarinya?', 'Luas = 3 × 2. Semak unitnya.'], s: ['Menutup bermaksud ruang di dalam → luas.', '3 × 2 = 6 m².'], w: { 'Perimeter = 10 m': 'Perimeternya 10 m, tetapi menutup berkaitan ruang di dalam.', 'Area = 10 m²': 'Luas = panjang × lebar.' }, y: { q: 'Kenapa jawapannya luas?', o: ['Menutup lantai bermaksud ruang di dalam', 'Kerana tikar itu segi empat tepat', 'Kerana luas sentiasa lebih besar'] } },
  'ra-1': { h: ['Warna manakah disebut dahulu?', 'Dalam nisbah, susunannya mengikut ayat: merah kepada biru.', 'Tulis bilangan merah, kemudian “:”, kemudian bilangan biru.'], s: ['Merah dahulu: 3. Biru kemudian: 2.', 'Nisbah merah kepada biru = 3 : 2.'], w: { '2 : 3': 'Susunan penting. Warna manakah disebut dahulu dalam soalan?', '3 : 5': '5 ialah semua manik. Bandingkan merah dengan biru.' } },
  'ra-2': { h: ['Berapa cawan air untuk 1 cawan beras?', 'Setiap cawan beras perlukan 2 cawan air sendiri.', 'Buat 3 baris: 1 beras → 2 air. Kira air.'], s: ['1 beras → 2 air.', '3 beras → 3 × 2 = 6 air.'], w: { '3': 'Itu beras. Kita perlukan air.', '5': 'Anda tambah 3 + 2. Setiap cawan beras perlukan 2 cawan air.' }, c: 'Semak: air dua kali ganda beras ✓' },
  'ra-3': { h: ['Apakah maksud 1 : 4 bagi satu kotak?', 'Setiap kotak ada 4 pensel. Berapa kotak?', '5 kotak × 4 pensel = ?'], s: ['1 kotak : 4 pensel.', '5 kotak → 5 × 4 = 20 pensel.'], w: { '9': 'Anda menambah. Setiap kotak ada 4 pensel.' } },
  'ra-4': { h: ['Buah manakah disebut dahulu?', 'Mangga dahulu, kemudian rambutan.', 'Kira mangga, kemudian rambutan.'], s: ['Mangga: 2. Rambutan: 6.', 'Nisbah = 2 : 6.'], w: { '6 : 2': 'Semak susunan dalam soalan.', '2 : 8': '8 ialah semua buah. Bandingkan mangga dengan rambutan.' } },
  'da-1': { h: ['Cari baris Bala.', 'Semak petunjuk: satu gambar mewakili berapa buku?', 'Kira gambar dalam baris Bala.'], s: ['1 gambar = 1 buku.', 'Baris Bala ada 6 gambar → 6 buku.'], w: { '13': 'Itu semua murid. Kita perlukan Bala sahaja.' } },
  'da-2': { h: ['Lihat petunjuk. Satu gambar mewakili berapa?', 'Satu gambar = 10 biji durian. Ada berapa gambar pada hari Selasa?', '5 gambar × 10 = ?'], s: ['Petunjuk: ● mewakili 10 biji durian.', 'Selasa ada 5 gambar: 5 × 10 = 50 biji durian.'], w: { '5': 'Anda mengira gambar. Semak petunjuk: setiap gambar mewakili 10.', '15': 'Setiap gambar mewakili 10, jadi darab, jangan tambah.' }, y: { q: 'Kenapa anda darab dengan 10?', o: ['Petunjuk menyatakan setiap gambar mewakili 10 biji durian', 'Kerana ada 10 hari', 'Kerana durian besar'] } },
  'da-3': { h: ['Kita membandingkan dua hari. Yang mana?', 'Cari durian setiap hari dengan petunjuk, kemudian bandingkan.', 'Selasa 5 × 10, Rabu 2 × 10. Cari bezanya.'], s: ['Selasa: 50. Rabu: 20.', '50 − 20 = 30 biji durian lebih.'], w: { '3': 'Itu 3 gambar. Guna petunjuk: setiap gambar mewakili 10.', '70': 'Anda menambah. “Berapa banyak lagi” bermaksud bandingkan.' } },
  'da-4': { h: ['Paling digemari bermaksud dipilih oleh paling ramai murid.', 'Lihat lajur Murid. Nombor manakah paling besar?', 'Bandingkan 14, 9 dan 11.'], s: ['Milo 14, Teh tarik 9, Sirap 11.', '14 paling besar → Milo.'], w: { 'Teh tarik': 'Teh tarik paling sedikit. Paling digemari mempunyai bilangan paling banyak.' } },
  'da-5': { h: ['“Jumlah keseluruhan” bermaksud semua kumpulan digabungkan.', 'Tambah semua nombor dalam lajur Murid.', '14 + 9 + 11: cuba 9 + 11 dahulu.'], s: ['9 + 11 = 20.', '20 + 14 = 34 orang murid.'], w: { '14': 'Itu Milo sahaja. Tambah semua minuman.', '23': 'Sudah tambah ketiga-tiga minuman?' } },
  'wp-1': { h: ['APA? Kita perlukan baki wang. Apa yang perlu diketahui dahulu?', 'BAGAIMANA? Langkah 1: cari harga 2 helai baju. Langkah 2: tolak daripada RM50.00.', 'BUAT: 2 × RM15.50 = RM31.00. Sekarang cari baki daripada RM50.00.'], s: ['Langkah 1: 2 × RM15.50 = RM31.00.', 'Langkah 2: RM50.00 − RM31.00 = RM19.00.'], w: { 'RM34.50': 'Anda tolak sehelai baju sahaja. Kak Ros membeli 2 helai.', 'RM31.00': 'Itu harga baju. Soalan bertanya baki wang.', 'RM29.00': 'Semak RM50.00 − RM31.00.' }, c: 'Semak: RM31.00 + RM19.00 = RM50.00 ✓' },
  'wp-2': { h: ['APA? Kita cari tempoh masa atau waktu tiba?', 'BAGAIMANA? Tambah jam dahulu, kemudian minit. Ingat 60 minit = 1 jam.', 'BUAT: 0950 + 2 jam = 1150. Sekarang tambah 25 minit: 1150 → 1200 ialah 10 minit.'], s: ['0950 + 2 jam = 1150.', '1150 + 10 minit = 1200, kemudian + 15 minit = 1215.', 'Kereta api tiba pada jam 1215.'], w: { '1175 hours': 'Minit hanya hingga 59. 75 minit ialah 1 jam 15 minit.', '1115 hours': 'Semak jam yang ditambah.' }, c: 'Semak: bahagian minit kurang daripada 60 ✓' },
  'wp-3': { h: ['APA? Kita cari kos. Apa yang perlu diukur dahulu?', 'BAGAIMANA? Langkah 1: cari perimeter. Langkah 2: darab dengan RM3.', 'BUAT: 8 + 5 + 8 + 5 = 26 m. Sekarang cari kos bagi 26 m.'], s: ['Perimeter: 8 + 5 + 8 + 5 = 26 m.', 'Kos: 26 × RM3 = RM78.'], w: { 'RM120': 'Anda guna luas. Pagar dipasang di sekeliling tepi.', 'RM26': '26 m ialah panjang pagar. Sekarang cari kosnya.', 'RM39': 'Semak: sudah kira semua sisi?' }, c: 'Semak: 26 m × RM3, jawapannya dalam ringgit ✓' },
  'wp-4': { h: ['APA? Kita cari baki guli Amir.', 'BAGAIMANA? Langkah 1: cari 1/4 daripada 36. Langkah 2: tolak daripada 36.', 'BUAT: 36 ÷ 4 = 9 biji guli diberi. Sekarang cari bakinya.'], s: ['1/4 daripada 36 = 36 ÷ 4 = 9.', '36 − 9 = 27 biji guli tinggal.'], w: { '9': '9 ialah yang diberi kepada adik. Soalan bertanya bakinya.', '32': '1/4 daripada 36 bukan 4. Bahagi 36 kepada 4 kumpulan.' }, c: 'Semak: 27 + 9 = 36 ✓' },
  'wp-5': { h: ['APA? Wang pada akhirnya. Apa berlaku dahulu, dan apa berlaku kemudian?', 'BAGAIMANA? Langkah 1: jumlah simpanan 6 minggu. Langkah 2: tolak harga hadiah.', 'BUAT: 6 × RM8 = RM48. Sekarang RM48.00 − RM19.50.'], s: ['Simpanan: 6 × RM8 = RM48.00.', 'RM48.00 − RM19.50 = RM28.50.'], w: { 'RM67.50': 'Berbelanja mengurangkan wang.', 'RM48.00': 'Itu wang yang disimpan. Pak Cik Kamal berbelanja selepas itu.', 'RM29.50': 'Semak RM48.00 − RM19.50 sekali lagi.' }, c: 'Semak: RM28.50 + RM19.50 = RM48.00 ✓' }
};

/* Step-back ladders in BM. `o` translates text options when they are words. */
FMQ.laddersBm = {
  'place-value': { intro: 'Mari lihat nilai tempat dahulu.', steps: [{ t: 'Dalam 352, digit manakah di tempat puluh?', h: 'Dari kanan: sa, kemudian puluh.' }, { t: 'Jadi digit 5 dalam 352 bernilai…', h: '5 puluh = 50.' }] },
  'add-sub': { intro: 'Mari tentukan: gabung atau banding?', steps: [{ t: 'Ali ada 9 biji epal. Dia makan 4 biji. Epalnya bertambah atau berkurang?', o: ['Berkurang', 'Bertambah'], h: 'Makan menyebabkan epal berkurang.' }, { t: 'Operasi manakah mengurangkan nilai?', o: ['Tolak (−)', 'Tambah (+)'], h: 'Mengambil keluar.' }] },
  'times-divide': { intro: 'Mari fikir dalam kumpulan sama banyak.', steps: [{ t: '3 pinggan, 4 biji kuih dalam setiap pinggan. Berapa biji kuih?', h: '4 + 4 + 4.' }, { t: '12 biji kuih dibahagi sama rata ke dalam 3 pinggan. Berapa biji dalam setiap pinggan?', h: 'Letak satu demi satu ke dalam pinggan.' }] },
  'decimals': { intro: 'Mari susun titik perpuluhan.', steps: [{ t: 'Yang manakah sama dengan 4.5?', h: 'Sifar di hujung nombor perpuluhan tidak mengubah nilainya.' }, { t: 'Berapakah 4.50 − 1.00?', h: 'Hanya sa yang berubah.' }] },
  'money': { intro: 'Mari fikir apa berlaku kepada wang.', steps: [{ t: 'Anda ada RM10. Anda membeli sebuah buku. Wang anda bertambah atau berkurang?', o: ['Berkurang', 'Bertambah'], h: 'Membayar menggunakan wang.' }, { t: 'Berapakah RM10.00 − RM4.00?', h: 'Tolak 4 daripada 10.' }, { t: 'Berapakah RM10.00 − RM4.50?', h: 'Tolak RM4, kemudian 50 sen lagi.' }] },
  'fractions': { intro: 'Mari lihat bahagian yang sama besar.', steps: [{ t: 'Sebiji kek dipotong kepada 3 bahagian sama besar. Satu bahagian ialah…', h: '1 bahagian daripada 3 bahagian sama besar.' }, { t: '1/3 daripada 9 biji gula-gula ialah…', h: 'Bahagi 9 kepada 3 kumpulan sama.' }] },
  'percent': { intro: 'Mari mula dengan “daripada 100”.', steps: [{ t: 'Peratus bermaksud…', o: ['daripada 100', 'daripada 10', 'darab 100'], h: '“Per-ratus”: setiap seratus.' }, { t: '4/10 = ?/100', h: 'Darab atas dan bawah dengan 10.' }] },
  'time24': { intro: 'Mari lihat sistem 24 jam.', steps: [{ t: 'Jam 12 tengah hari dalam sistem 24 jam ialah…', h: 'Tengah hari ialah 12.' }, { t: '2:00 p.m. ialah…', h: '2 + 12 = 14.' }] },
  'duration': { intro: 'Mari kira masa dalam lompatan kecil.', steps: [{ t: 'Dari 1:00 p.m. hingga 2:00 p.m. ialah…', h: 'Jam naik satu.' }, { t: '1 jam ialah berapa minit?', h: 'Fikir tentang muka jam.' }] },
  'measure': { intro: 'Mari jadikan unitnya sama.', steps: [{ t: '1 kg = ? g', h: '“Kilo” bermaksud 1 000.' }, { t: '1 liter = ? ml', h: '“Mili” bermaksud perseribu.' }] },
  'perimeter': { intro: 'Mari berjalan mengelilingi bentuk.', steps: [{ t: 'Perimeter ialah…', o: ['jarak di sekeliling tepi', 'ruang di dalam', 'sisi paling panjang'], h: 'Bayangkan semut berjalan mengelilingi bentuk.' }, { t: 'Sebuah segi tiga ada sisi 3 cm, 4 cm dan 5 cm. Perimeternya ialah…', h: 'Tambah ketiga-tiga sisi.' }] },
  'area': { intro: 'Mari kira petak.', steps: [{ t: 'Ada berapa petak?', h: '2 baris, setiap baris 3.' }, { t: '2 baris, setiap baris 3 petak, sama dengan…', h: 'Baris petak yang sama banyak → darab.' }] },
  'ratio': { intro: 'Mari bandingkan dua kumpulan.', steps: [{ t: '2 ekor kucing dan 5 ekor anjing. Nisbah kucing kepada anjing ialah…', h: 'Kucing dahulu, kemudian anjing.' }, { t: '1 basikal ada 2 roda. 4 basikal ada…', o: ['8 roda', '6 roda', '2 roda'], h: '4 × 2.' }] },
  'data': { intro: 'Mari baca petunjuk dahulu.', steps: [{ t: 'Petunjuk: ★ = 2 bintang. Berapakah ★★★?', h: 'Setiap ★ bernilai 2.' }, { t: 'Dalam jadual, nombor paling besar menunjukkan…', o: ['yang paling banyak', 'yang paling sedikit', 'yang di tengah'], h: 'Nombor besar, lebih banyak.' }] },
  'shapes': { intro: 'Mari lihat bahagian sesuatu bentuk.', steps: [{ t: 'Penjuru sesuatu bentuk dipanggil…', o: ['bucu', 'muka', 'tepi'], h: 'Bucu ialah penjuru.' }, { t: 'Penjuru segi empat, seperti penjuru buku, ialah…', o: ['sudut tegak', 'garis lurus', 'bulatan'], h: 'Sudut tegak berbentuk L.' }] },
  'coordinates': { intro: 'Mari berlatih “melintang, kemudian ke atas”.', steps: [{ t: 'Dalam (2, 5), nombor manakah menunjukkan jarak MELINTANG?', h: 'Nombor pertama ialah melintang.' }, { t: 'Mula di (0, 0). Gerak 3 melintang dan 1 ke atas. Di mana anda?', h: 'Melintang dahulu, kemudian ke atas.' }] },
  'word-problems': { intro: 'Mari pecahkan kepada langkah kecil.', steps: [{ t: 'Soalan yang panjang selalunya ada…', o: ['lebih daripada satu langkah', 'satu nombor sahaja', 'tiada jawapan'], h: 'Cari perkataan “dahulu” dan “kemudian”.' }, { t: 'Yang mana perlu dicari dahulu: apa yang anda TAHU atau apa yang anda PERLU cari?', o: ['Apa yang perlu dicari', 'Nombor paling besar'], h: 'APA yang soalan tanya?' }] },
  'clock': { intro: 'Mari kenal jam dari asas.', steps: [{ t: 'Jarum PENDEK pada jam menunjukkan…', o: ['jam', 'minit', 'saat'], h: 'Jarum pendek = jam. Jarum panjang = minit.' }, { t: 'Jarum panjang menunjuk ke 12. Ini bermaksud…', o: ['tepat (0 minit)', '12 minit', 'setengah jam'], h: 'Di 12, minitnya 0: pukul tepat.' }, { t: 'Setiap nombor pada jam bernilai berapa minit untuk jarum panjang?', h: 'Kira 5-5: 5, 10, 15…' }] },
  'basic-facts': { intro: 'Mari kira dengan mudah.', steps: [{ t: '7 + 3 = ?', h: '7, kemudian kira 3 lagi: 8, 9, 10.' }, { t: '10 − 4 = ?', h: 'Mula di 10, kira ke belakang 4.' }] },
  'times-tables': { intro: 'Mari kira lompat.', steps: [{ t: '3 + 3 + 3 + 3 sama dengan…', h: '4 kumpulan 3 = 4 × 3.' }, { t: 'Kira lompat 5: 5, 10, 15, … Nombor seterusnya?', h: 'Tambah 5 lagi.' }] }
};

/* English ladders for the new foundation skills (the BM is above). */
FMQ.ladders.clock = { intro: 'Let’s meet the clock from the start.', steps: [
  { text: 'The SHORT hand on a clock shows the…', options: ['hour', 'minutes', 'seconds'], answer: 'hour', hint: 'Short hand = hour. Long hand = minutes.' },
  { text: 'The long hand points to 12. That means…', options: ['o’clock (0 minutes)', '12 minutes', 'half past'], answer: 'o’clock (0 minutes)', hint: 'At 12, the minutes are 0: o’clock.', visual: { kind: 'clock', h: 3, m: 0 } },
  { text: 'For the long hand, each number on the clock is worth how many minutes?', options: ['5', '1', '10'], answer: '5', hint: 'Count in 5s: 5, 10, 15…' }] };
FMQ.ladders['basic-facts'] = { intro: 'Let’s count simply.', steps: [
  { text: '7 + 3 = ?', options: ['10', '4', '11'], answer: '10', hint: 'Start at 7, count on 3: 8, 9, 10.' },
  { text: '10 − 4 = ?', options: ['6', '14', '5'], answer: '6', hint: 'Start at 10 and count back 4.' }] };
FMQ.ladders['times-tables'] = { intro: 'Let’s skip-count.', steps: [
  { text: '3 + 3 + 3 + 3 is the same as…', options: ['4 × 3', '3 + 4', '4 + 4 + 4'], answer: '4 × 3', hint: '4 groups of 3 = 4 × 3.' },
  { text: 'Skip-count in 5s: 5, 10, 15, … What comes next?', options: ['20', '16', '25'], answer: '20', hint: 'Add 5 more.' }] };

/* Merge BM into the question and ladder objects. */
(function () {
  FMQ.questions.forEach(function (q) {
    var b = FMQ.questionsBm[q.id]; if (!b) return;
    q.hintsBm = b.h; q.showBm = b.s; q.checkBm = b.c;
    Object.keys(q.wrong || {}).forEach(function (k) { if (b.w && b.w[k]) q.wrong[k] = [q.wrong[k][0], q.wrong[k][1], b.w[k]]; });
    if (q.why && b.y) { q.why.qBm = b.y.q; q.why.optionsBm = b.y.o; }
    if (q.confuse && b.cf) {
      q.confuse.introBm = b.cf.intro;
      q.confuse.steps.forEach(function (st, i) { var x = b.cf.steps[i] || {}; st.textBm = x.t; st.hintBm = x.h; if (x.o) st.optionsBm = x.o; });
    }
  });
  Object.keys(FMQ.laddersBm).forEach(function (k) {
    var l = FMQ.ladders[k], b = FMQ.laddersBm[k]; if (!l) return;
    l.introBm = b.intro;
    l.steps.forEach(function (st, i) { var x = b.steps[i] || {}; st.textBm = x.t; st.hintBm = x.h; if (x.o) st.optionsBm = x.o; });
  });
})();
