/* Question bank.
   level: 1 foundation · 2 normal · 3 changed / context · 4 mini boss (multi-step)
   diag:  used in the first short diagnostic
   vocab: Word Bridge words that appear in the text
   hints: [notice, strategy, one step together]  — never the final answer
   show:  the short worked explanation (📘 Show Me How)
   bm / simple: sentence-level Word Bridge support (never contains the answer)
   wrong: { option: [errorCategory, nudge] } — nudge is shown after a wrong try
   check: the CHECK step shown after a correct answer
   why:   optional "How did you know?" reasoning question (+3 stars)
   confuse: optional question-specific ladder for 😕 I'm Confused
   related: (mini boss) skills this problem also uses */
window.FMQ = window.FMQ || {};

FMQ.questions = [
  /* ───────── Place value ───────── */
  { id: 'pv-1', skill: 'place-value', level: 1,
    text: 'In 4 572, what is the value of the digit 5?',
    options: ['5', '50', '500', '5 000'], answer: '500', vocab: ['value', 'digit'],
    hints: ['Which place is the 5 in: ones, tens, hundreds or thousands?', 'Count the places from the right: ones, tens, hundreds…', 'The 5 is in the hundreds place. What is 5 hundreds?'],
    show: ['4 572 = 4 thousands, 5 hundreds, 7 tens, 2 ones.', '5 hundreds = 500.'],
    bm: 'Dalam nombor 4 572, apakah nilai digit 5?', simple: 'Look at 4 572. How much is the 5 worth?',
    wrong: { '5': ['CONCEPT', 'The digit is 5, but its place makes it worth more. Which place is it in?'], '50': ['CONCEPT', 'Count the places again from the right.'] } },
  { id: 'pv-2', skill: 'place-value', level: 2,
    text: 'Which number is 3 000 more than 25 406?',
    options: ['25 706', '28 406', '55 406', '25 409'], answer: '28 406', vocab: ['more than'],
    hints: ['Which place does 3 000 change: hundreds or thousands?', 'Only the thousands digit should change.', '25 406 has 5 thousands. Add 3 more thousands.'],
    show: ['3 000 is 3 thousands.', '25 406 → the thousands digit 5 becomes 8.', '25 406 + 3 000 = 28 406.'],
    bm: 'Nombor manakah 3 000 lebih daripada 25 406?', simple: 'Start at 25 406. Add 3 000. Which number do you get?',
    wrong: { '25 706': ['CONCEPT', 'You changed the hundreds. 3 000 changes a different place.'], '55 406': ['CONCEPT', 'You changed the ten thousands. Check which place 3 000 belongs to.'], '25 409': ['CONCEPT', 'You changed the ones. 3 000 is much bigger than 3.'] } },
  { id: 'pv-3', skill: 'place-value', level: 3,
    text: 'The school library has 2 thousands, 4 hundreds and 9 ones books.\nHow many books are there?',
    options: ['2 490', '2 409', '249', '24 009'], answer: '2 409', vocab: [],
    hints: ['Which places are mentioned? Is any place missing?', 'Write a digit for each place: thousands, hundreds, tens, ones.', 'There are no tens. What digit do we write for zero tens?'],
    show: ['Thousands 2, hundreds 4, tens 0, ones 9.', 'The number is 2 409.'],
    bm: 'Perpustakaan sekolah ada 2 ribu, 4 ratus dan 9 sa buku. Berapakah bilangan buku?', simple: 'There are 2 thousands, 4 hundreds, 0 tens and 9 ones. Write the number.',
    wrong: { '2 490': ['CONCEPT', 'Check the tens place. Were any tens mentioned?'], '249': ['CONCEPT', 'Every place needs a digit, even when it is zero.'] } },
  { id: 'pv-4', skill: 'place-value', level: 1,
    text: 'Which is the largest number?',
    options: ['9 870', '10 200', '9 999', '10 020'], answer: '10 200', vocab: ['largest'],
    hints: ['Which numbers have the most digits?', 'Compare 10 200 and 10 020 digit by digit from the left.', 'Both start with 10. Compare the hundreds digit next.'],
    show: ['10 200 and 10 020 have 5 digits, so they are bigger than the 4-digit numbers.', 'Hundreds: 2 is more than 0, so 10 200 is the largest.'],
    bm: 'Nombor manakah yang paling besar?', simple: 'Which number is the biggest?',
    wrong: { '9 999': ['CONCEPT', '9 999 looks big, but count the digits of the other numbers.'], '10 020': ['EXECUTE', 'Compare the hundreds digits of 10 020 and 10 200.'] } },

  /* ───────── Adding & subtracting ───────── */
  { id: 'as-1', skill: 'add-sub', level: 1,
    text: 'What is 254 + 138?',
    options: ['382', '392', '492', '316'], answer: '392', vocab: [],
    hints: ['Add the ones first.', '4 + 8 = 12. What do we do with the 1 ten?', 'Carry the 1 into the tens: 5 + 3 + 1.'],
    show: ['Ones: 4 + 8 = 12 → write 2, carry 1.', 'Tens: 5 + 3 + 1 = 9.', 'Hundreds: 2 + 1 = 3.', 'Answer: 392.'],
    bm: 'Berapakah 254 + 138?', simple: 'Add 254 and 138.',
    wrong: { '382': ['EXECUTE', 'Check the carry from the ones column.'], '492': ['EXECUTE', 'Check the hundreds column.'], '316': ['PLAN', 'This is an add question. Look at the sign.'] } },
  { id: 'as-2', skill: 'add-sub', level: 2, diag: true,
    text: 'What is the difference between 80 and 35?',
    options: ['115', '45', '55', '35'], answer: '45', vocab: ['difference'],
    hints: ['What does “difference” ask us to do with two numbers?', 'To compare two numbers, we find how far apart they are. Which operation helps?', 'Start at 80 and take away 35. Take away 30 first.'],
    show: ['Difference means subtract the smaller number from the bigger one.', '80 − 35 = 45.'],
    bm: 'Apakah perbezaan antara 80 dan 35?', simple: 'How far apart are 80 and 35?',
    wrong: { '115': ['UNDERSTAND', 'You added. “Difference” compares the two numbers.'], '55': ['EXECUTE', 'Check the subtraction: 80 − 30 first, then − 5.'], '35': ['UNDERSTAND', 'That is one of the numbers in the question. Compare 80 and 35.'] },
    check: 'Check: 35 + 45 = 80 ✓',
    why: { q: 'How did you know to subtract?', options: ['“Difference” means compare two numbers', 'Because 80 is an even number', 'There are two numbers, so we always subtract'], answer: 0 } },
  { id: 'as-3', skill: 'add-sub', level: 3,
    text: 'Hakim has 125 stickers.\nMei Ling has 60 stickers.\nHow many more stickers does Hakim have?',
    options: ['185', '65', '75', '55'], answer: '65', vocab: ['how many more'],
    hints: ['Are we finding a total, or comparing two amounts?', '“How many more” compares two amounts. Which operation?', 'Do 125 − 60. Take away 6 tens from 12 tens.'],
    show: ['“How many more” means find the difference.', '125 − 60 = 65.', 'Hakim has 65 more stickers.'],
    bm: 'Hakim ada 125 pelekat. Mei Ling ada 60 pelekat. Berapa banyak lagi pelekat Hakim berbanding Mei Ling?', simple: 'Hakim has 125. Mei Ling has 60. How much bigger is Hakim’s number?',
    wrong: { '185': ['UNDERSTAND', 'You found the total. The question compares the two amounts.'] },
    check: 'Check: 60 + 65 = 125 ✓' },
  { id: 'as-4', skill: 'add-sub', level: 3,
    text: 'A bakery made 1 250 kuih.\n875 were sold.\nHow many kuih are remaining?',
    options: ['475', '375', '2 125', '385'], answer: '375', vocab: ['sold', 'remaining'],
    hints: ['What happened to the kuih that were sold?', 'Some kuih are gone. Should the number become bigger or smaller?', 'Write 1 250 and put 875 underneath. Start with the ones: 0 − 5 needs regrouping.'],
    show: ['Remaining means what is still there.', '1 250 − 875 = 375.', '375 kuih are remaining.'],
    bm: 'Sebuah kedai roti membuat 1 250 kuih. 875 biji telah dijual. Berapakah baki kuih?', simple: 'There were 1 250 kuih. 875 are gone. How many are still there?',
    wrong: { '2 125': ['UNDERSTAND', 'You added. Sold kuih are no longer there.'], '475': ['EXECUTE', 'Check the regrouping in the hundreds.'], '385': ['EXECUTE', 'Check the tens column.'] },
    check: 'Check: 875 + 375 = 1 250 ✓' },
  { id: 'as-5', skill: 'add-sub', level: 2,
    text: 'Class 4 Bestari has 32 pupils.\nClass 4 Cemerlang has 29 pupils.\nHow many pupils are there altogether?',
    options: ['51', '3', '61', '71'], answer: '61', vocab: ['altogether'],
    hints: ['Are we joining the classes or comparing them?', '“Altogether” joins amounts. Which operation?', '32 + 29: add 30 first, then take away 1.'],
    show: ['Altogether means add.', '32 + 29 = 61.'],
    bm: 'Kelas 4 Bestari ada 32 murid. Kelas 4 Cemerlang ada 29 murid. Berapakah jumlah keseluruhan murid?', simple: 'Put both classes together. How many pupils?',
    wrong: { '3': ['UNDERSTAND', 'You found the difference. “Altogether” joins the groups.'], '51': ['EXECUTE', 'Check the tens: 3 tens + 2 tens + the carried ten.'] } },

  /* ───────── Times & sharing ───────── */
  { id: 'td-1', skill: 'times-divide', level: 1,
    text: 'What is 6 × 7?',
    options: ['36', '42', '48', '13'], answer: '42', vocab: [],
    hints: ['6 × 7 means 6 groups of 7.', 'Do you know 6 × 6? Add one more 6.', '6 × 6 = 36. Now add 6.'],
    show: ['6 × 6 = 36.', '36 + 6 = 42.'],
    bm: 'Berapakah 6 × 7?', simple: 'What is 6 groups of 7?',
    wrong: { '13': ['PLAN', 'You added. × means groups of.'], '36': ['EXECUTE', 'That is 6 × 6. We need one more group.'], '48': ['EXECUTE', 'That is 6 × 8. Try one group less.'] } },
  { id: 'td-2', skill: 'times-divide', level: 2, diag: true,
    text: 'There are 48 sweets.\nThey are shared equally among 6 children.\nHow many sweets does each child get?',
    options: ['6', '7', '8', '42'], answer: '8', vocab: ['shared equally', 'each'],
    hints: ['What happens to the sweets? Are they joined or shared?', 'Sharing equally into groups uses division.', 'Find 48 ÷ 6. Which number times 6 makes 48?'],
    show: ['Shared equally means divide.', '48 ÷ 6 = 8, because 6 × 8 = 48.', 'Each child gets 8 sweets.'],
    bm: 'Ada 48 biji gula-gula. Gula-gula itu dikongsi sama rata antara 6 orang kanak-kanak. Berapakah bilangan gula-gula yang diterima oleh setiap kanak-kanak?', simple: '48 sweets. 6 children get the same number. How many does one child get?',
    wrong: { '42': ['PLAN', 'You subtracted. Sharing equally uses a different operation.'], '7': ['EXECUTE', 'Check: 6 × 7 = 42, not 48.'] },
    check: 'Check: 6 × 8 = 48 ✓',
    why: { q: 'Why did you divide?', options: ['The sweets were shared into equal groups', 'Because 48 is bigger than 6', 'Division is always used for sweets'], answer: 0 } },
  { id: 'td-3', skill: 'times-divide', level: 3,
    text: 'A box holds 24 pencils.\nHow many pencils are in 5 boxes?',
    options: ['29', '100', '120', '124'], answer: '120', vocab: ['holds'],
    hints: ['Each box has the same number of pencils. How many boxes?', 'Equal groups put together: which operation?', '24 × 5: do 20 × 5 and 4 × 5, then add.'],
    show: ['5 boxes of 24 → 24 × 5.', '20 × 5 = 100, 4 × 5 = 20.', '100 + 20 = 120 pencils.'],
    bm: 'Sebuah kotak memuatkan 24 batang pensel. Berapakah bilangan pensel dalam 5 buah kotak?', simple: 'One box has 24 pencils. There are 5 boxes. How many pencils?',
    wrong: { '29': ['PLAN', 'You added 24 and 5. There are 5 groups of 24.'], '100': ['EXECUTE', 'You did 20 × 5. Don’t forget the 4 × 5.'] } },
  { id: 'td-4', skill: 'times-divide', level: 2,
    text: 'What is 156 ÷ 4?',
    options: ['39', '38', '41', '152'], answer: '39', vocab: [],
    hints: ['How many 4s are in 156?', 'Split 156 into 120 and 36. Both divide by 4 easily.', '120 ÷ 4 = 30. Now find 36 ÷ 4.'],
    show: ['156 = 120 + 36.', '120 ÷ 4 = 30, 36 ÷ 4 = 9.', '30 + 9 = 39.'],
    bm: 'Berapakah 156 ÷ 4?', simple: 'Share 156 into 4 equal groups. How many in each group?',
    wrong: { '152': ['PLAN', 'You subtracted 4. ÷ means share into groups.'] },
    check: 'Check: 39 × 4 = 156 ✓' },
  { id: 'td-5', skill: 'times-divide', level: 3,
    text: 'Puan Aida puts 63 eggs into trays.\nEach tray holds 9 eggs.\nHow many trays does she fill?',
    options: ['7', '8', '54', '72'], answer: '7', vocab: ['each', 'trays', 'holds'],
    hints: ['We know the total eggs and how many fit in one tray. What are we finding?', 'Splitting a total into equal groups uses division.', 'Find 63 ÷ 9. Which number times 9 is 63?'],
    show: ['63 ÷ 9 = 7, because 9 × 7 = 63.', 'She fills 7 trays.'],
    bm: 'Puan Aida memasukkan 63 biji telur ke dalam dulang. Setiap dulang memuatkan 9 biji telur. Berapakah bilangan dulang yang penuh?', simple: '63 eggs. 9 eggs go in one tray. How many trays?',
    wrong: { '54': ['PLAN', 'You subtracted 9 once. Keep making groups of 9.'], '72': ['PLAN', 'You added. The eggs are being split into trays.'] } },

  /* ───────── Decimals ───────── */
  { id: 'dec-1', skill: 'decimals', level: 1,
    text: 'What is 5.6 − 2.3?',
    options: ['3.3', '3.9', '7.9', '3.03'], answer: '3.3', vocab: [],
    hints: ['Line up the decimal points first.', 'Subtract the tenths, then the ones.', 'Tenths: 6 − 3. Ones: 5 − 2.'],
    show: ['5.6 − 2.3', 'Tenths: 6 − 3 = 3. Ones: 5 − 2 = 3.', 'Answer: 3.3.'],
    bm: 'Berapakah 5.6 − 2.3?', simple: 'Take 2.3 away from 5.6.',
    wrong: { '7.9': ['PLAN', 'You added. Look at the sign.'], '3.03': ['CONCEPT', 'Keep the digits in the same places as the question.'] } },
  { id: 'dec-2', skill: 'decimals', level: 2, diag: true,
    text: 'What is 7.2 − 3.45?',
    options: ['4.27', '3.75', '4.85', '3.85'], answer: '3.75',
    vocab: [],
    hints: ['How many decimal places does each number have?', 'Write 7.2 as 7.20 so both numbers have two decimal places.', 'Now line up the points: 7.20 − 3.45. Start from the hundredths: 0 − 5 needs regrouping.'],
    show: ['7.2 = 7.20.', '7.20 − 3.45: regroup, then subtract each column.', 'Answer: 3.75.'],
    bm: 'Berapakah 7.2 − 3.45?', simple: 'Take 3.45 away from 7.2.',
    wrong: { '4.27': ['CONCEPT', 'The decimal points were not lined up. Write 7.2 as 7.20 first.'], '4.85': ['EXECUTE', 'In each column, take the bottom digit from the top digit. You may need to regroup.'], '3.85': ['EXECUTE', 'Check the tenths after regrouping.'] },
    check: 'Check: 3.75 + 3.45 = 7.20 ✓',
    confuse: { intro: 'Let’s line up decimals first.', steps: [
      { text: 'Which is the same as 7.2?', options: ['7.20', '7.02', '72'], answer: '7.20', hint: 'Adding a zero at the end of the decimal does not change it.' },
      { text: 'What is 7.20 − 3.00?', options: ['4.20', '10.20', '4.02'], answer: '4.20', hint: 'Only the ones change: 7 − 3.' },
      { text: 'What is 0.50 − 0.45?', options: ['0.05', '0.95', '0.15'], answer: '0.05', hint: '50 hundredths take away 45 hundredths.' }
    ] } },
  { id: 'dec-3', skill: 'decimals', level: 3,
    text: 'A ribbon is 4.5 m long.\nSiti cuts off 1.75 m.\nHow long is the ribbon now?',
    options: ['2.75 m', '3.25 m', '2.85 m', '6.25 m'], answer: '2.75 m', vocab: ['cuts off', 'how long'],
    hints: ['After cutting, is the ribbon longer or shorter?', 'Shorter means subtract. Give both numbers two decimal places.', 'Write 4.50 − 1.75 with the points lined up.'],
    show: ['4.5 m = 4.50 m.', '4.50 − 1.75 = 2.75.', 'The ribbon is now 2.75 m.'],
    bm: 'Seutas reben panjangnya 4.5 m. Siti memotong 1.75 m. Berapakah panjang reben itu sekarang?', simple: 'A ribbon is 4.5 m. Siti cuts 1.75 m away. How long is it now?',
    wrong: { '6.25 m': ['UNDERSTAND', 'You added. Cutting makes the ribbon shorter.'], '3.25 m': ['CONCEPT', 'Line up the decimal points: write 4.5 as 4.50.'] },
    check: 'Check: 2.75 + 1.75 = 4.50 ✓' },
  { id: 'dec-4', skill: 'decimals', level: 1,
    text: 'Which decimal is the same as 7/10?',
    options: ['7.10', '0.7', '0.07', '7.0'], answer: '0.7', vocab: [],
    hints: ['7/10 means 7 tenths.', 'Tenths are the first place after the decimal point.', 'Write 0, then the point, then 7 in the tenths place.'],
    show: ['7/10 = 7 tenths = 0.7.'],
    bm: 'Nombor perpuluhan manakah sama dengan 7/10?', simple: 'Write 7 tenths as a decimal.',
    wrong: { '0.07': ['CONCEPT', '0.07 is 7 hundredths. We need tenths.'], '7.10': ['CONCEPT', 'The fraction line is not a decimal point.'] } },
  { id: 'dec-5', skill: 'decimals', level: 2,
    text: 'What is 10 − 6.4?',
    options: ['4.6', '3.6', '4.4', '16.4'], answer: '3.6', vocab: [],
    hints: ['Write 10 as a decimal with one decimal place.', '10 = 10.0. Now line up the points.', '10.0 − 6.4: regroup a one into 10 tenths.'],
    show: ['10.0 − 6.4', 'Regroup: 9 ones and 10 tenths.', '10 tenths − 4 tenths = 6 tenths; 9 − 6 = 3.', 'Answer: 3.6.'],
    bm: 'Berapakah 10 − 6.4?', simple: 'Take 6.4 away from 10.',
    wrong: { '4.6': ['EXECUTE', 'Check the regrouping in the ones.'], '16.4': ['PLAN', 'You added. Look at the sign.'], '4.4': ['CONCEPT', 'Write 10 as 10.0 before subtracting.'] },
    check: 'Check: 3.6 + 6.4 = 10 ✓' },

  /* ───────── Money ───────── */
  { id: 'mon-1', skill: 'money', level: 2, diag: true, sample: true,
    text: 'Aina has RM30.00.\nShe spends RM12.50.\nHow much money does she have left?',
    options: ['RM17.50', 'RM18.50', 'RM22.50', 'RM42.50'], answer: 'RM17.50', vocab: ['spends', 'left'],
    hints: ['What are we trying to find?', 'Aina starts with money and then spends some. Should the amount become bigger or smaller?', 'Start with RM30.00 and place RM12.50 underneath it. Keep the decimal points aligned.'],
    show: ['Spending makes the money smaller, so subtract.', 'RM30.00 − RM12.50', 'Keep the points lined up and regroup.', 'RM30.00 − RM12.50 = RM17.50.'],
    bm: 'Aina ada RM30.00. Dia membelanjakan RM12.50. Berapakah baki wang Aina?', simple: 'Aina has RM30.00. She uses RM12.50 to buy things. How much money does she still have?',
    wrong: { 'RM42.50': ['UNDERSTAND', 'You added. When Aina spends money, does she have more or less?'], 'RM18.50': ['EXECUTE', 'Check the ones column after regrouping.'], 'RM22.50': ['EXECUTE', 'Check the tens column.'] },
    check: 'Check: RM17.50 + RM12.50 = RM30.00 ✓',
    why: { q: 'How did you know to subtract?', options: ['Spending makes the money smaller', 'The numbers have decimal points', 'Money questions always use subtract'], answer: 0 } },
  { id: 'mon-2', skill: 'money', level: 1,
    text: 'A pen costs RM2.50.\nA ruler costs RM1.20.\nWhat is the total cost?',
    options: ['RM3.50', 'RM3.70', 'RM1.30', 'RM37.00'], answer: 'RM3.70', vocab: ['costs', 'total'],
    hints: ['Are we joining the prices or comparing them?', '“Total” means add.', 'Add the sen first: 50 sen + 20 sen.'],
    show: ['Total means add.', 'RM2.50 + RM1.20 = RM3.70.'],
    bm: 'Sebatang pen berharga RM2.50. Sebatang pembaris berharga RM1.20. Berapakah jumlah harganya?', simple: 'Pen RM2.50. Ruler RM1.20. How much for both?',
    wrong: { 'RM1.30': ['UNDERSTAND', 'You found the difference. “Total” joins the prices.'], 'RM37.00': ['CONCEPT', 'Keep the decimal points lined up.'] } },
  { id: 'mon-3', skill: 'money', level: 3,
    text: 'Ravi pays RM20.00 for a book that costs RM13.60.\nHow much change does he get?',
    options: ['RM7.40', 'RM6.40', 'RM6.60', 'RM33.60'], answer: 'RM6.40', vocab: ['pays', 'costs', 'change'],
    hints: ['What is “change” in a shop?', 'Change is what is left from the money he paid. Which operation?', 'Write RM20.00 − RM13.60 with the decimal points lined up.'],
    show: ['Change = money paid − price.', 'RM20.00 − RM13.60 = RM6.40.'],
    bm: 'Ravi membayar RM20.00 untuk sebuah buku yang berharga RM13.60. Berapakah baki wang yang dia terima?', simple: 'Ravi gives RM20.00. The book is RM13.60. How much money comes back to him?',
    wrong: { 'RM33.60': ['UNDERSTAND', 'You added. Change is what comes back after paying.'], 'RM7.40': ['EXECUTE', 'Check the ones after regrouping.'], 'RM6.60': ['EXECUTE', 'Check the sen: 100 − 60.'] },
    check: 'Check: RM13.60 + RM6.40 = RM20.00 ✓' },
  { id: 'mon-4', skill: 'money', level: 2, diag: true,
    text: 'Nasi lemak costs RM4.50 a packet.\nMother buys 3 packets.\nHow much does she pay?',
    options: ['RM7.50', 'RM13.00', 'RM13.50', 'RM12.50'], answer: 'RM13.50', vocab: ['costs', 'buys'],
    hints: ['How many packets, and what does one packet cost?', '3 packets at the same price: you can multiply or add 3 times.', 'RM4.50 × 3: do RM4 × 3 and 50 sen × 3.'],
    show: ['RM4 × 3 = RM12.', '50 sen × 3 = RM1.50.', 'RM12 + RM1.50 = RM13.50.'],
    bm: 'Sebungkus nasi lemak berharga RM4.50. Ibu membeli 3 bungkus. Berapakah yang ibu bayar?', simple: 'One packet is RM4.50. Mother takes 3 packets. How much money?',
    wrong: { 'RM7.50': ['PLAN', 'You added 3 once. She buys 3 packets at RM4.50 each.'], 'RM13.00': ['EXECUTE', 'Check the sen part: 50 sen × 3.'] },
    why: { q: 'Why can you multiply here?', options: ['Each packet costs the same, so it is 3 equal groups', 'Because 4.50 has a decimal', 'Multiplying always makes the answer right'], answer: 0 } },
  { id: 'mon-5', skill: 'money', level: 3,
    text: 'Farah has RM15.00.\nShe buys a drink for RM2.80.\nHow much money is remaining?',
    options: ['RM12.20', 'RM13.20', 'RM12.80', 'RM17.80'], answer: 'RM12.20', vocab: ['buys', 'remaining'],
    hints: ['What happens to Farah’s money when she buys a drink?', 'Less money remains, so subtract.', 'RM15.00 − RM2.80: take away RM3, then add back 20 sen.'],
    show: ['RM15.00 − RM2.80', 'RM15.00 − RM3.00 = RM12.00, then + 20 sen.', 'RM12.20 remaining.'],
    bm: 'Farah ada RM15.00. Dia membeli minuman berharga RM2.80. Berapakah baki wangnya?', simple: 'Farah has RM15.00. A drink is RM2.80. How much does she still have?',
    wrong: { 'RM17.80': ['UNDERSTAND', 'You added. Buying uses up some money.'], 'RM12.80': ['EXECUTE', 'Check the sen: 100 − 80.'], 'RM13.20': ['EXECUTE', 'Check the ringgit after regrouping.'] },
    check: 'Check: RM12.20 + RM2.80 = RM15.00 ✓' },

  /* ───────── Fractions ───────── */
  { id: 'fr-1', skill: 'fractions', level: 1,
    text: 'This bar is cut into 4 equal parts.\nWhat fraction is shaded?',
    visual: { kind: 'bar', parts: 4, shaded: 1 },
    options: ['1/3', '1/4', '4/1', '3/4'], answer: '1/4', vocab: ['equal parts', 'shaded'],
    hints: ['How many equal parts are there?', 'The bottom number shows all the parts. The top number shows the shaded parts.', 'Count the shaded parts. That goes on top.'],
    show: ['4 equal parts → bottom number 4.', '1 part shaded → top number 1.', 'Fraction: 1/4.'],
    bm: 'Bar ini dibahagi kepada 4 bahagian yang sama besar. Apakah pecahan yang berlorek?', simple: 'The bar has 4 same-size parts. What fraction is coloured?',
    wrong: { '1/3': ['CONCEPT', 'The bottom number counts all the parts, not only the unshaded ones.'], '4/1': ['CONCEPT', 'Which number goes on top: shaded parts or all parts?'], '3/4': ['UNDERSTAND', 'That is the unshaded part.'] } },
  { id: 'fr-2', skill: 'fractions', level: 2, diag: true, sample: true,
    text: 'What is 3/4 of 20?',
    options: ['5', '12', '15', '60'], answer: '15', vocab: ['of'],
    hints: ['What does the 4 in 3/4 tell you to do with 20?', 'First find 1/4 of 20 by sharing 20 into 4 equal groups.', '1/4 of 20 is one group. 3/4 is three of those groups.'],
    show: ['20 ÷ 4 = 5, so 1/4 of 20 = 5.', '3/4 is 3 groups: 3 × 5 = 15.'],
    bm: 'Berapakah 3/4 daripada 20?', simple: 'Share 20 into 4 equal groups. How much is in 3 of the groups?',
    wrong: { '5': ['PLAN', 'That is 1/4 of 20. We need 3 parts.'], '60': ['CONCEPT', 'You multiplied 20 by 3. First share 20 into 4 groups.'], '12': ['EXECUTE', 'Check 20 ÷ 4 first.'] },
    check: 'Check: 15 is less than 20, which makes sense for 3/4 ✓',
    confuse: { intro: 'Before we solve that, let’s look at quarters.', steps: [
      { text: 'If something is divided into 4 equal parts, what does 1/4 mean?', visual: { kind: 'bar', parts: 4, shaded: 1 }, options: ['1 of the 4 equal parts', '4 whole things', '1 part out of 2'], answer: '1 of the 4 equal parts', hint: 'Look at the bar. One part is shaded out of 4 equal parts.' },
      { text: '20 sweets are shared into 4 equal groups.\nHow many sweets are in 1 group?', visual: { kind: 'dots', total: 20, groups: 4 }, options: ['4', '5', '16'], answer: '5', hint: 'Count the dots in one group.' },
      { text: 'So 1/4 of 20 is 5.\nWhat is 2/4 of 20?', visual: { kind: 'dots', total: 20, groups: 4, highlight: 2 }, options: ['10', '2', '40'], answer: '10', hint: '2 groups of 5.' }
    ] } },
  { id: 'fr-3', skill: 'fractions', level: 3,
    text: 'There are 12 cupcakes.\n2/3 of them are chocolate.\nHow many chocolate cupcakes are there?',
    options: ['4', '8', '6', '9'], answer: '8', vocab: ['of'],
    hints: ['What does the 3 in 2/3 tell you to do?', 'Share 12 into 3 equal groups first.', '1/3 of 12 is one group. How many groups do we need?'],
    show: ['12 ÷ 3 = 4, so 1/3 of 12 = 4.', '2/3 = 2 groups: 2 × 4 = 8.'],
    bm: 'Ada 12 biji kek cawan. 2/3 daripadanya ialah kek coklat. Berapakah bilangan kek cawan coklat?', simple: '12 cupcakes in 3 equal groups. 2 groups are chocolate. How many chocolate?',
    wrong: { '4': ['PLAN', 'That is 1/3. We need 2 groups.'], '6': ['CONCEPT', 'That is half of 12. Look at the fraction again.'] },
    check: 'Check: 8 is less than 12 ✓' },
  { id: 'fr-4', skill: 'fractions', level: 1,
    text: 'Which fraction is equal to 1/2?',
    visual: { kind: 'bar', parts: 2, shaded: 1 },
    options: ['1/4', '2/3', '2/4', '3/4'], answer: '2/4', vocab: ['equal'],
    hints: ['Half means one of two equal parts.', 'If the bar had 4 parts, how many would be shaded to make the same amount?', 'Split each half into 2. Count the shaded quarters.'],
    show: ['Cut each half into 2 pieces → 4 pieces.', '2 of the 4 pieces are shaded.', '1/2 = 2/4.'],
    bm: 'Pecahan manakah sama dengan 1/2?', simple: 'Which fraction is the same amount as one half?',
    wrong: { '1/4': ['CONCEPT', '1/4 is smaller than a half.'], '3/4': ['CONCEPT', '3/4 is bigger than a half.'] } },
  { id: 'fr-5', skill: 'fractions', level: 2,
    text: 'What is 1/5 of 30?',
    options: ['5', '6', '25', '150'], answer: '6', vocab: ['of'],
    hints: ['1/5 means one of 5 equal parts.', 'Share 30 into 5 equal groups.', 'How many 5s make 30?'],
    show: ['30 ÷ 5 = 6.', '1/5 of 30 = 6.'],
    bm: 'Berapakah 1/5 daripada 30?', simple: 'Share 30 into 5 equal groups. How many in one group?',
    wrong: { '150': ['CONCEPT', 'You multiplied. A fraction of an amount is smaller than the amount.'], '25': ['PLAN', 'You subtracted 5. Share 30 into 5 groups instead.'] } },

  /* ───────── Percentages ───────── */
  { id: 'pc-1', skill: 'percent', level: 1,
    text: 'Write 50/100 as a percentage.',
    options: ['5%', '50%', '100%', '0.5%'], answer: '50%', vocab: ['percentage'],
    hints: ['Percent means “out of 100”.', 'The fraction already has 100 at the bottom.', 'The top number becomes the percentage.'],
    show: ['50/100 means 50 out of 100.', '50 out of 100 = 50%.'],
    bm: 'Tulis 50/100 sebagai peratus.', simple: '50 out of 100. What is that as a percent?',
    wrong: { '5%': ['CONCEPT', 'Out of 100, the top number tells us the percent.'] } },
  { id: 'pc-2', skill: 'percent', level: 2, diag: true,
    text: '7/10 = ?%',
    options: ['7%', '70%', '17%', '710%'], answer: '70%', vocab: [],
    hints: ['Percent means out of 100. What is the bottom number now?', 'Change 10 into 100. What do you multiply by?', 'Multiply the top and bottom by 10.'],
    show: ['7/10 = 70/100 (multiply top and bottom by 10).', '70/100 = 70%.'],
    bm: '7/10 bersamaan dengan berapa peratus?', simple: 'Write 7 tenths as a percent.',
    wrong: { '7%': ['CONCEPT', '7% is 7 out of 100. Our fraction is out of 10.'], '17%': ['CONCEPT', 'We don’t add the numbers. Make the bottom 100.'], '710%': ['CONCEPT', 'Percent means out of 100. Make the bottom number 100.'] },
    confuse: { intro: 'Let’s start with “out of 100”.', steps: [
      { text: 'Percent means…', options: ['out of 100', 'out of 10', 'times 100'], answer: 'out of 100', hint: '“Cent” is like 100, as in “century”.' },
      { text: '3/10 = ?/100', options: ['30/100', '3/100', '13/100'], answer: '30/100', hint: '10 × 10 = 100, so 3 × 10 on top.' },
      { text: '30/100 = ?%', options: ['30%', '3%', '300%'], answer: '30%', hint: 'Out of 100, the top number is the percent.' }
    ] } },
  { id: 'pc-3', skill: 'percent', level: 3,
    text: 'There are 10 flowers.\n6 are red.\nWhat percentage are red?',
    visual: { kind: 'flowers', total: 10, red: 6 },
    options: ['6%', '60%', '40%', '16%'], answer: '60%', vocab: ['percentage'],
    hints: ['Write the red flowers as a fraction first.', '6 out of 10 = 6/10. Now make the bottom 100.', 'Multiply the top and bottom of 6/10 by 10.'],
    show: ['6 out of 10 = 6/10.', '6/10 = 60/100 = 60%.'],
    bm: 'Ada 10 kuntum bunga. 6 kuntum berwarna merah. Berapakah peratus bunga merah?', simple: '6 of the 10 flowers are red. What percent are red?',
    wrong: { '6%': ['CONCEPT', 'There are 10 flowers, not 100. Change to “out of 100”.'], '40%': ['UNDERSTAND', 'That is the flowers that are not red.'] },
    check: 'Check: more than half are red, and 60% is more than 50% ✓' },
  { id: 'pc-4', skill: 'percent', level: 2,
    text: 'Write 1/4 as a percentage.',
    options: ['14%', '25%', '40%', '4%'], answer: '25%', vocab: ['percentage'],
    hints: ['What do you multiply 4 by to make 100?', '4 × 25 = 100. Do the same to the top.', '1 × 25 = ?'],
    show: ['1/4 = 25/100.', '25/100 = 25%.'],
    bm: 'Tulis 1/4 sebagai peratus.', simple: 'One quarter is how many percent?',
    wrong: { '14%': ['CONCEPT', 'We don’t write the digits side by side. Make the bottom 100.'], '4%': ['CONCEPT', 'Change the bottom number to 100 first.'] } },
  { id: 'pc-5', skill: 'percent', level: 3,
    text: 'A pizza is cut into 10 equal slices.\nAmin eats 3 slices.\nWhat percentage of the pizza is left?',
    options: ['30%', '70%', '3%', '7%'], answer: '70%', vocab: ['equal', 'left', 'percentage'],
    hints: ['Are we finding the slices eaten or the slices left?', 'How many slices are left out of 10?', '7 out of 10 left. Change 7/10 into a percentage.'],
    show: ['10 − 3 = 7 slices left.', '7/10 = 70/100 = 70%.'],
    bm: 'Sebiji piza dipotong kepada 10 keping yang sama besar. Amin makan 3 keping. Berapakah peratus piza yang tinggal?', simple: '10 slices. Amin eats 3. What percent is still there?',
    wrong: { '30%': ['UNDERSTAND', 'That is the part Amin ate. The question asks what is left.'], '7%': ['CONCEPT', 'Change 7/10 to “out of 100” first.'] },
    check: 'Check: 70% + 30% = 100% ✓' },

  /* ───────── 24-hour time ───────── */
  { id: 't24-1', skill: 'time24', level: 1,
    text: 'Which 24-hour time is the same as 3:00 p.m.?',
    options: ['0300 hours', '1300 hours', '1500 hours', '0315 hours'], answer: '1500 hours', vocab: [],
    hints: ['p.m. times are after 12 noon.', 'For p.m. times, add 12 to the hour.', '3 + 12 = ?'],
    show: ['3:00 p.m. is in the afternoon.', '3 + 12 = 15.', '3:00 p.m. = 1500 hours.'],
    bm: 'Waktu 24 jam manakah sama dengan 3:00 p.m.?', simple: '3:00 in the afternoon. What is it in 24-hour time?',
    wrong: { '0300 hours': ['CONCEPT', '0300 hours is 3 in the early morning. p.m. is after noon.'], '1300 hours': ['EXECUTE', '1300 hours is 1:00 p.m. Add 12 to 3.'] } },
  { id: 't24-2', skill: 'time24', level: 2, diag: true,
    text: 'The school bus leaves at 1845 hours.\nWhat time is this in 12-hour time?',
    visual: { kind: 'clock24', time: '1845' },
    options: ['8:45 p.m.', '6:45 a.m.', '6:45 p.m.', '4:45 p.m.'], answer: '6:45 p.m.', vocab: ['leaves'],
    hints: ['Is 1845 hours before or after 12 noon?', 'After noon, take away 12 from the hour.', '18 − 12 = ? Keep the 45 minutes.'],
    show: ['18 is more than 12, so it is p.m.', '18 − 12 = 6.', '1845 hours = 6:45 p.m.'],
    bm: 'Bas sekolah bertolak pada jam 1845. Apakah waktu itu dalam sistem 12 jam?', simple: 'The bus goes at 1845 hours. Write the time with a.m. or p.m.',
    wrong: { '8:45 p.m.': ['CONCEPT', 'We take away 12, not 10.'], '6:45 a.m.': ['CONCEPT', '18 is after noon, so it is p.m.'], '4:45 p.m.': ['EXECUTE', 'Check 18 − 12.'] },
    confuse: { intro: 'Let’s look at how the 24-hour clock works.', steps: [
      { text: '12 noon in 24-hour time is…', options: ['1200 hours', '0000 hours', '2400 hours'], answer: '1200 hours', hint: 'Noon is the middle of the day: 12.' },
      { text: '1 hour after noon is 1:00 p.m.\nIn 24-hour time it is…', options: ['1300 hours', '0100 hours', '1100 hours'], answer: '1300 hours', hint: 'Keep counting after 12: 13.' },
      { text: 'So 1600 hours is…', options: ['4:00 p.m.', '6:00 p.m.', '4:00 a.m.'], answer: '4:00 p.m.', hint: '16 − 12 = 4, and it is after noon.' }
    ] } },
  { id: 't24-3', skill: 'time24', level: 3,
    text: 'A shop closes at 9:30 p.m.\nWhich 24-hour time shows this?',
    options: ['0930 hours', '2130 hours', '1930 hours', '2330 hours'], answer: '2130 hours', vocab: ['closes'],
    hints: ['Is 9:30 p.m. in the morning or at night?', 'For p.m. times, add 12 to the hour.', '9 + 12 = ? Keep the 30 minutes.'],
    show: ['9:30 p.m. is at night.', '9 + 12 = 21.', '9:30 p.m. = 2130 hours.'],
    bm: 'Sebuah kedai ditutup pada 9:30 p.m. Waktu 24 jam manakah menunjukkan waktu ini?', simple: 'The shop shuts at 9:30 at night. Write it in 24-hour time.',
    wrong: { '0930 hours': ['CONCEPT', '0930 hours is in the morning.'], '1930 hours': ['EXECUTE', 'Add 12, not 10.'] } },
  { id: 't24-4', skill: 'time24', level: 1,
    text: 'Which 24-hour time is in the afternoon?',
    options: ['0900 hours', '1100 hours', '0600 hours', '1400 hours'], answer: '1400 hours', vocab: ['afternoon'],
    hints: ['Afternoon starts after 12 noon.', 'Which time has an hour bigger than 12?', 'Look at the first two digits of each time.'],
    show: ['Afternoon times have hours after 12.', '1400 hours = 2:00 p.m.'],
    bm: 'Waktu 24 jam manakah pada waktu petang?', simple: 'Which time is after 12 noon?',
    wrong: { '1100 hours': ['CONCEPT', '11 is before 12 noon.'] } },

  /* ───────── Duration ───────── */
  { id: 'du-1', skill: 'duration', level: 1,
    text: 'How many minutes are in 1 hour?',
    options: ['100', '60', '24', '30'], answer: '60', vocab: [],
    hints: ['Think about a clock. How many minutes until the long hand goes all the way round?', 'Half an hour is 30 minutes.', 'Double 30.'],
    show: ['1 hour = 60 minutes.'],
    bm: 'Berapakah bilangan minit dalam 1 jam?', simple: '1 hour has how many minutes?',
    wrong: { '100': ['CONCEPT', 'Time is not counted in hundreds. Think of the clock.'], '24': ['CONCEPT', '24 is the hours in a day.'] } },
  { id: 'du-2', skill: 'duration', level: 2, diag: true,
    text: 'A movie starts at 2:15 p.m. and ends at 4:00 p.m.\nWhat is the duration of the movie?',
    options: ['2 hours 15 minutes', '1 hour 45 minutes', '1 hour 15 minutes', '6 hours 15 minutes'], answer: '1 hour 45 minutes', vocab: ['starts', 'ends', 'duration'],
    hints: ['Duration is the time from start to end.', 'Count on from 2:15 p.m. to 3:15 p.m. first.', '2:15 to 3:15 is 1 hour. How many minutes from 3:15 to 4:00?'],
    show: ['2:15 → 3:15 = 1 hour.', '3:15 → 4:00 = 45 minutes.', 'Duration = 1 hour 45 minutes.'],
    bm: 'Sebuah filem bermula pada 2:15 p.m. dan tamat pada 4:00 p.m. Berapakah tempoh masa filem itu?', simple: 'The movie begins at 2:15 p.m. It finishes at 4:00 p.m. How long is it?',
    wrong: { '6 hours 15 minutes': ['UNDERSTAND', 'You added the times. Duration counts from the start to the end.'], '2 hours 15 minutes': ['EXECUTE', 'Count on from 2:15. Is 4:00 more than 2 hours later?'], '1 hour 15 minutes': ['EXECUTE', 'An hour has 60 minutes, not 100. Count the minutes from 3:15 to 4:00.'] },
    check: 'Check: 2:15 + 1 hour 45 minutes = 4:00 ✓',
    confuse: { intro: 'Let’s count time in small jumps.', steps: [
      { text: 'From 2:00 p.m. to 3:00 p.m. is…', options: ['1 hour', '30 minutes', '2 hours'], answer: '1 hour', hint: 'The hour number goes up by one.' },
      { text: 'From 3:30 p.m. to 4:00 p.m. is…', options: ['30 minutes', '70 minutes', '1 hour'], answer: '30 minutes', hint: 'Half an hour.' },
      { text: 'So 2:00 p.m. → 3:00 p.m. → 3:30 p.m. is…', options: ['1 hour 30 minutes', '3 hours 30 minutes', '1 hour'], answer: '1 hour 30 minutes', hint: 'Add the jumps: 1 hour, then 30 minutes.' }
    ] } },
  { id: 'du-3', skill: 'duration', level: 3,
    text: 'Tuition begins at 1430 hours.\nIt lasts 1 hour 20 minutes.\nWhat time does it end?',
    options: ['1450 hours', '1550 hours', '1610 hours', '1530 hours'], answer: '1550 hours', vocab: ['begins', 'lasts'],
    hints: ['Are we finding the duration or the end time?', 'Add the time it lasts to the start time.', 'Add 1 hour first: 1430 → 1530. Then add 20 minutes.'],
    show: ['1430 + 1 hour = 1530.', '1530 + 20 minutes = 1550.', 'Tuition ends at 1550 hours.'],
    bm: 'Kelas tuisyen bermula pada jam 1430. Kelas itu berlangsung selama 1 jam 20 minit. Pukul berapakah kelas itu tamat?', simple: 'Tuition starts at 1430 hours. It goes on for 1 hour 20 minutes. When does it finish?',
    wrong: { '1450 hours': ['EXECUTE', 'You added the minutes. Did you add the hour too?'], '1530 hours': ['EXECUTE', 'You added the hour. Now add the 20 minutes.'] },
    check: 'Check: 1550 is after 1430 ✓' },
  { id: 'du-4', skill: 'duration', level: 2,
    text: 'Convert 2 hours 10 minutes to minutes.',
    options: ['210 minutes', '130 minutes', '120 minutes', '70 minutes'], answer: '130 minutes', vocab: ['convert'],
    hints: ['How many minutes are in 1 hour?', '2 hours = 2 × 60 minutes.', '120 minutes + 10 minutes = ?'],
    show: ['2 hours = 120 minutes.', '120 + 10 = 130 minutes.'],
    bm: 'Tukar 2 jam 10 minit kepada minit.', simple: 'Write 2 hours 10 minutes using only minutes.',
    wrong: { '210 minutes': ['CONCEPT', '1 hour is 60 minutes, not 100.'], '120 minutes': ['EXECUTE', 'Don’t forget the extra 10 minutes.'] } },
  { id: 'du-5', skill: 'duration', level: 3,
    text: 'Danial reads from 0845 hours to 0930 hours.\nHow long does he read?',
    options: ['85 minutes', '45 minutes', '55 minutes', '1 hour 45 minutes'], answer: '45 minutes', vocab: ['how long'],
    hints: ['We need the time between two clock times.', 'Count on from 0845 to 0900 first.', '0845 → 0900 is 15 minutes. Then 0900 → 0930?'],
    show: ['0845 → 0900 = 15 minutes.', '0900 → 0930 = 30 minutes.', '15 + 30 = 45 minutes.'],
    bm: 'Danial membaca dari jam 0845 hingga jam 0930. Berapa lamakah dia membaca?', simple: 'Danial reads from 0845 hours. He stops at 0930 hours. How many minutes?',
    wrong: { '85 minutes': ['CONCEPT', 'You subtracted like normal numbers. An hour has 60 minutes, so count on instead.'] },
    check: 'Check: 0845 + 45 minutes = 0930 ✓' },

  /* ───────── Measurement ───────── */
  { id: 'me-1', skill: 'measure', level: 1,
    text: 'How many centimetres are in 1 metre?',
    options: ['10', '100', '1 000', '60'], answer: '100', vocab: [],
    hints: ['Think of a metre ruler.', '“Centi” means hundredth.', '1 m = ? cm'],
    show: ['1 m = 100 cm.'],
    bm: 'Berapakah bilangan sentimeter dalam 1 meter?', simple: '1 m is how many cm?',
    wrong: { '1 000': ['CONCEPT', '1 000 is for kilo (1 km = 1 000 m).'], '10': ['CONCEPT', '1 cm = 10 mm. Think of a metre ruler.'] } },
  { id: 'me-2', skill: 'measure', level: 2, diag: true,
    text: 'A bottle has 1 litre of water.\nAli pours out 350 ml.\nHow much water is left?',
    options: ['750 ml', '650 ml', '1 350 ml', '350 ml'], answer: '650 ml', vocab: ['pours out', 'left'],
    hints: ['Are the units the same? Litres and millilitres.', 'Change 1 litre into millilitres first.', '1 litre = 1 000 ml. Now take away 350 ml.'],
    show: ['1 l = 1 000 ml.', '1 000 ml − 350 ml = 650 ml.'],
    bm: 'Sebuah botol berisi 1 liter air. Ali menuang keluar 350 ml. Berapakah isi padu air yang tinggal?', simple: 'The bottle has 1 litre. Ali takes out 350 ml. How much is still inside?',
    wrong: { '1 350 ml': ['UNDERSTAND', 'You added. Pouring out makes it less.'], '750 ml': ['EXECUTE', 'Check 1 000 − 350.'], '350 ml': ['UNDERSTAND', 'That is the water poured out, not the water left.'] },
    check: 'Check: 650 ml + 350 ml = 1 000 ml ✓' },
  { id: 'me-3', skill: 'measure', level: 3,
    text: 'A bag of rice has a mass of 2 kg.\nMother uses 500 g.\nWhat is the mass of rice remaining?',
    options: ['1 500 g', '2 500 g', '1 000 g', '1 050 g'], answer: '1 500 g', vocab: ['mass', 'remaining'],
    hints: ['Are kg and g the same unit?', 'Change 2 kg into grams.', '2 kg = 2 000 g. Take away 500 g.'],
    show: ['2 kg = 2 000 g.', '2 000 g − 500 g = 1 500 g.'],
    bm: 'Sebungkus beras mempunyai jisim 2 kg. Ibu menggunakan 500 g. Berapakah jisim beras yang tinggal?', simple: 'The rice weighs 2 kg. Mother uses 500 g. How much rice is still there?',
    wrong: { '2 500 g': ['UNDERSTAND', 'You added. Mother used some rice.'], '1 050 g': ['CONCEPT', 'Change 2 kg into grams first: 1 kg = 1 000 g.'] } },
  { id: 'me-4', skill: 'measure', level: 2,
    text: 'Convert 3 kg to grams.',
    options: ['300 g', '30 g', '3 000 g', '3 100 g'], answer: '3 000 g', vocab: ['convert'],
    hints: ['How many grams are in 1 kg?', '1 kg = 1 000 g.', '3 × 1 000 = ?'],
    show: ['1 kg = 1 000 g.', '3 kg = 3 000 g.'],
    bm: 'Tukar 3 kg kepada gram.', simple: 'Write 3 kg in grams.',
    wrong: { '300 g': ['CONCEPT', '1 kg is 1 000 g, not 100 g.'] } },

  /* ───────── Perimeter ───────── */
  { id: 'pe-1', skill: 'perimeter', level: 1,
    text: 'A square has sides of 5 cm.\nWhat is its perimeter?',
    visual: { kind: 'rect', w: 5, h: 5, unit: 'cm' },
    options: ['25 cm', '20 cm', '10 cm', '15 cm'], answer: '20 cm', vocab: ['perimeter'],
    hints: ['How many sides does a square have?', 'Perimeter adds all the sides around the shape.', '5 + 5 + 5 + 5 = ?'],
    show: ['A square has 4 equal sides.', '5 + 5 + 5 + 5 = 20 cm.'],
    bm: 'Sebuah segi empat sama mempunyai sisi 5 cm. Berapakah perimeternya?', simple: 'Each side of the square is 5 cm. How far is it all the way around?',
    wrong: { '25 cm': ['CONCEPT', '5 × 5 is the area. Perimeter goes around the edge.'], '10 cm': ['EXECUTE', 'A square has 4 sides, not 2.'] } },
  { id: 'pe-2', skill: 'perimeter', level: 2, diag: true,
    text: 'A rectangle is 8 cm long and 3 cm wide.\nWhat is its perimeter?',
    visual: { kind: 'rect', w: 8, h: 3, unit: 'cm' },
    options: ['24 cm', '11 cm', '22 cm', '14 cm'], answer: '22 cm', vocab: ['wide', 'perimeter'],
    hints: ['Perimeter means all the way around. How many sides?', 'A rectangle has 2 long sides and 2 short sides.', '8 + 3 + 8 + 3 = ?'],
    show: ['Sides: 8, 3, 8, 3.', '8 + 3 + 8 + 3 = 22 cm.'],
    bm: 'Sebuah segi empat tepat panjangnya 8 cm dan lebarnya 3 cm. Berapakah perimeternya?', simple: 'The rectangle is 8 cm by 3 cm. How far is it all the way around?',
    wrong: { '24 cm': ['CONCEPT', '8 × 3 is the area. Perimeter adds the sides around.'], '11 cm': ['EXECUTE', 'That is only 2 sides. A rectangle has 4.'] },
    why: { q: 'Why did you add all four sides?', options: ['Perimeter is the whole distance around the edge', 'Because adding is easier', 'Because the shape is long'], answer: 0 } },
  { id: 'pe-3', skill: 'perimeter', level: 3,
    text: 'Encik Lim puts a fence around his garden.\nThe garden is 10 m long and 6 m wide.\nHow many metres of fence does he need?',
    visual: { kind: 'rect', w: 10, h: 6, unit: 'm' },
    options: ['60 m', '32 m', '16 m', '26 m'], answer: '32 m', vocab: ['fence', 'around', 'wide'],
    hints: ['Does the fence go around the edge or cover the inside?', 'Around the edge means perimeter.', '10 + 6 + 10 + 6 = ?'],
    show: ['The fence goes around → perimeter.', '10 + 6 + 10 + 6 = 32 m.'],
    bm: 'Encik Lim memasang pagar di sekeliling kebunnya. Kebun itu panjangnya 10 m dan lebarnya 6 m. Berapa meter pagar yang diperlukan?', simple: 'The garden is 10 m by 6 m. The fence goes all the way round. How long is the fence?',
    wrong: { '60 m': ['PLAN', 'You found the area. A fence goes around the edge.'], '16 m': ['EXECUTE', 'That is two sides. Go all the way round.'] },
    check: 'Check: the answer is in metres (m), a length ✓' },
  { id: 'pe-4', skill: 'perimeter', level: 3,
    text: 'A square photo frame has a perimeter of 36 cm.\nHow long is one side?',
    options: ['6 cm', '9 cm', '18 cm', '12 cm'], answer: '9 cm', vocab: ['perimeter'],
    hints: ['A square has 4 equal sides.', '4 equal sides make 36 cm. Which operation finds one side?', '36 ÷ 4 = ?'],
    show: ['4 equal sides = 36 cm.', '36 ÷ 4 = 9 cm.'],
    bm: 'Sebuah bingkai gambar berbentuk segi empat sama mempunyai perimeter 36 cm. Berapakah panjang satu sisi?', simple: 'All 4 sides together are 36 cm. How long is one side?',
    wrong: { '6 cm': ['CONCEPT', '6 × 6 = 36 is for area. A square has 4 sides.'], '18 cm': ['EXECUTE', 'A square has 4 sides, not 2.'] },
    check: 'Check: 9 + 9 + 9 + 9 = 36 ✓' },

  /* ───────── Area ───────── */
  { id: 'ar-1', skill: 'area', level: 1,
    text: 'Each small square is 1 cm².\nWhat is the area of the shaded shape?',
    visual: { kind: 'grid', cols: 4, rows: 3 },
    options: ['7 cm²', '12 cm²', '14 cm²', '10 cm²'], answer: '12 cm²', vocab: ['area'],
    hints: ['Area is the space inside. What can you count?', 'Count the shaded squares. Try counting rows.', '3 rows of 4 squares.'],
    show: ['3 rows × 4 squares = 12 squares.', 'Area = 12 cm².'],
    bm: 'Setiap petak kecil ialah 1 cm². Berapakah luas bentuk berlorek?', simple: 'Count the coloured squares. Each one is 1 cm².',
    wrong: { '14 cm²': ['CONCEPT', 'You counted around the edge. Area counts the squares inside.'], '7 cm²': ['CONCEPT', 'You added 4 + 3. Count all the squares.'] } },
  { id: 'ar-2', skill: 'area', level: 2, diag: true,
    text: 'A rectangle is 6 cm long and 4 cm wide.\nWhat is its area?',
    visual: { kind: 'rect', w: 6, h: 4, unit: 'cm', grid: true },
    options: ['20 cm²', '24 cm²', '10 cm²', '24 cm'], answer: '24 cm²', vocab: ['wide', 'area'],
    hints: ['Area is the space inside the rectangle.', 'Area of a rectangle = length × width.', '6 × 4 = ? Check the unit too.'],
    show: ['Area = length × width.', '6 × 4 = 24.', 'Area = 24 cm² (square centimetres).'],
    bm: 'Sebuah segi empat tepat panjangnya 6 cm dan lebarnya 4 cm. Berapakah luasnya?', simple: 'The rectangle is 6 cm by 4 cm. How much space is inside?',
    wrong: { '20 cm²': ['PLAN', '20 is the perimeter. Area is the space inside.'], '24 cm': ['CHECK', 'The number is right. Area uses square units.'], '10 cm²': ['PLAN', 'You added. Area multiplies length and width.'] } },
  { id: 'ar-3', skill: 'area', level: 3,
    text: 'A classroom floor is 9 m long and 7 m wide.\nWhat is the area of the floor?',
    options: ['32 m²', '63 m²', '16 m²', '56 m²'], answer: '63 m²', vocab: ['wide', 'area'],
    hints: ['Is the floor’s area the edge or the space inside?', 'Length × width.', '9 × 7 = ?'],
    show: ['Area = 9 × 7 = 63.', 'Area = 63 m².'],
    bm: 'Lantai sebuah bilik darjah panjangnya 9 m dan lebarnya 7 m. Berapakah luas lantai itu?', simple: 'The floor is 9 m by 7 m. How much floor space?',
    wrong: { '32 m²': ['PLAN', '32 is the perimeter. Area is the space inside.'], '56 m²': ['EXECUTE', 'That is 8 × 7. Check 9 × 7.'] } },
  { id: 'ar-4', skill: 'area', level: 3,
    text: 'A mat is 3 m long and 2 m wide.\nAisyah wants to know how much floor the mat will cover.\nWhich is correct?',
    options: ['Perimeter = 10 m', 'Area = 6 m²', 'Area = 10 m²', 'Perimeter = 6 m'], answer: 'Area = 6 m²', vocab: ['wide', 'cover'],
    hints: ['Covering the floor is about the edge or the space inside?', 'The space inside is area. How do we find it?', 'Area = 3 × 2. Check the unit.'],
    show: ['Covering means the space inside → area.', '3 × 2 = 6 m².'],
    bm: 'Sebidang tikar panjangnya 3 m dan lebarnya 2 m. Aisyah ingin tahu berapa banyak lantai yang diliputi oleh tikar itu. Yang manakah betul?', simple: 'The mat is 3 m by 2 m. How much floor is under the mat?',
    wrong: { 'Perimeter = 10 m': ['PLAN', 'The perimeter is 10 m, but covering is about the space inside.'], 'Area = 10 m²': ['PLAN', 'Area multiplies length × width.'] },
    why: { q: 'Why is it area?', options: ['Covering the floor means the space inside', 'Because the mat is a rectangle', 'Because area is always bigger'], answer: 0 } },

  /* ───────── Ratio ───────── */
  { id: 'ra-1', skill: 'ratio', level: 1,
    text: 'There are 3 red beads and 2 blue beads.\nWhat is the ratio of red beads to blue beads?',
    visual: { kind: 'beads', groups: [{ n: 3, tone: 'a', label: 'red' }, { n: 2, tone: 'b', label: 'blue' }] },
    options: ['2 : 3', '3 : 2', '3 : 5', '5 : 3'], answer: '3 : 2', vocab: ['ratio'],
    hints: ['Which colour is mentioned first?', 'In a ratio, the order follows the words: red to blue.', 'Write the number of red, then “:”, then the number of blue.'],
    show: ['Red first: 3. Blue second: 2.', 'Ratio of red to blue = 3 : 2.'],
    bm: 'Ada 3 manik merah dan 2 manik biru. Apakah nisbah manik merah kepada manik biru?', simple: 'Red beads: 3. Blue beads: 2. Write red : blue.',
    wrong: { '2 : 3': ['UNDERSTAND', 'The order matters. Which colour comes first in the question?'], '3 : 5': ['CONCEPT', '5 is all the beads. Compare red with blue.'] } },
  { id: 'ra-2', skill: 'ratio', level: 2, diag: true,
    text: 'For every 1 cup of rice, Mak uses 2 cups of water.\nHow many cups of water does she need for 3 cups of rice?',
    visual: { kind: 'ratioRows', a: 'rice', b: 'water', ra: 1, rb: 2, rows: 1 },
    options: ['5', '4', '6', '3'], answer: '6', vocab: ['for every'],
    hints: ['How much water goes with 1 cup of rice?', 'Each cup of rice needs its own 2 cups of water.', 'Make 3 rows: 1 rice → 2 water. Count the water.'],
    show: ['1 rice → 2 water.', '3 rice → 3 × 2 = 6 water.'],
    bm: 'Bagi setiap 1 cawan beras, Mak menggunakan 2 cawan air. Berapakah cawan air yang diperlukan untuk 3 cawan beras?', simple: '1 cup of rice needs 2 cups of water. Mak cooks 3 cups of rice. How many cups of water?',
    wrong: { '5': ['PLAN', 'You added 3 + 2. Each cup of rice needs 2 cups of water.'], '3': ['UNDERSTAND', 'That is the rice. We need the water.'] },
    check: 'Check: water is double the rice ✓' },
  { id: 'ra-3', skill: 'ratio', level: 3,
    text: 'The ratio of boxes to pencils is 1 : 4.\nHow many pencils are in 5 boxes?',
    options: ['9', '20', '5', '4'], answer: '20', vocab: ['ratio'],
    hints: ['What does 1 : 4 tell us about one box?', 'Each box has 4 pencils. How many boxes?', '5 boxes × 4 pencils = ?'],
    show: ['1 box : 4 pencils.', '5 boxes → 5 × 4 = 20 pencils.'],
    bm: 'Nisbah kotak kepada pensel ialah 1 : 4. Berapakah bilangan pensel dalam 5 kotak?', simple: '1 box has 4 pencils. How many pencils in 5 boxes?',
    wrong: { '9': ['PLAN', 'You added. Each box has 4 pencils.'] } },
  { id: 'ra-4', skill: 'ratio', level: 2,
    text: 'A basket has 2 mangoes and 6 rambutans.\nWhat is the ratio of mangoes to rambutans?',
    visual: { kind: 'beads', groups: [{ n: 2, tone: 'c', label: 'mangoes' }, { n: 6, tone: 'a', label: 'rambutans' }] },
    options: ['6 : 2', '2 : 8', '2 : 6', '8 : 2'], answer: '2 : 6', vocab: ['ratio'],
    hints: ['Which fruit is mentioned first?', 'Mangoes first, then rambutans.', 'Count the mangoes, then the rambutans.'],
    show: ['Mangoes: 2. Rambutans: 6.', 'Ratio = 2 : 6.'],
    bm: 'Sebuah bakul ada 2 biji mangga dan 6 biji rambutan. Apakah nisbah mangga kepada rambutan?', simple: 'Mangoes: 2. Rambutans: 6. Write mangoes : rambutans.',
    wrong: { '6 : 2': ['UNDERSTAND', 'Check the order in the question.'], '2 : 8': ['CONCEPT', '8 is all the fruit. Compare mangoes with rambutans.'] } },

  /* ───────── Data ───────── */
  { id: 'da-1', skill: 'data', level: 1,
    text: 'The pictograph shows books read by three pupils.\nHow many books did Bala read?',
    visual: { kind: 'picto', title: 'Books read this month', icon: '📕', key: 1, unit: 'book', rows: [['Aina', 4], ['Bala', 6], ['Chen', 3]] },
    options: ['4', '6', '3', '13'], answer: '6', vocab: [],
    hints: ['Find Bala’s row.', 'Check the key: how many books does one picture show?', 'Count the pictures in Bala’s row.'],
    show: ['1 picture = 1 book.', 'Bala’s row has 6 pictures → 6 books.'],
    bm: 'Piktograf menunjukkan buku yang dibaca oleh tiga orang murid. Berapakah buku yang dibaca oleh Bala?', simple: 'Look at Bala’s row. How many books?',
    wrong: { '13': ['UNDERSTAND', 'That is everyone together. We only need Bala.'] } },
  { id: 'da-2', skill: 'data', level: 2, diag: true,
    text: 'The pictograph shows durians sold at a stall.\nHow many durians were sold on Tuesday?',
    visual: { kind: 'picto', title: 'Durians sold', icon: '●', key: 10, unit: 'durians', rows: [['Monday', 3], ['Tuesday', 5], ['Wednesday', 2]] },
    options: ['5', '50', '10', '15'], answer: '50', vocab: ['sold'],
    hints: ['Look at the key. What does one picture represent?', 'One picture = 10 durians. How many pictures on Tuesday?', '5 pictures × 10 = ?'],
    show: ['Key: ● represents 10 durians.', 'Tuesday has 5 pictures: 5 × 10 = 50 durians.'],
    bm: 'Piktograf menunjukkan durian yang dijual di sebuah gerai. Berapakah durian yang dijual pada hari Selasa?', simple: 'Look at Tuesday. Each ● means 10 durians. How many durians?',
    wrong: { '5': ['CHECK', 'You counted the pictures. Check the key: each picture means 10.'], '15': ['EXECUTE', 'Each picture is 10, so multiply, don’t add.'] },
    why: { q: 'Why did you multiply by 10?', options: ['The key says each picture represents 10 durians', 'Because there are 10 days', 'Because durians are big'], answer: 0 } },
  { id: 'da-3', skill: 'data', level: 3,
    text: 'How many more durians were sold on Tuesday than on Wednesday?',
    visual: { kind: 'picto', title: 'Durians sold', icon: '●', key: 10, unit: 'durians', rows: [['Monday', 3], ['Tuesday', 5], ['Wednesday', 2]] },
    options: ['3', '30', '70', '20'], answer: '30', vocab: ['how many more', 'sold'],
    hints: ['We are comparing two days. Which two?', 'Find each day’s durians using the key, then compare.', 'Tuesday 5 × 10, Wednesday 2 × 10. Find the difference.'],
    show: ['Tuesday: 50. Wednesday: 20.', '50 − 20 = 30 more durians.'],
    bm: 'Berapa banyak lagi durian dijual pada hari Selasa berbanding hari Rabu?', simple: 'Tuesday and Wednesday: how much bigger is Tuesday’s number?',
    wrong: { '3': ['CHECK', 'That is 3 pictures. Use the key: each picture is 10.'], '70': ['UNDERSTAND', 'You added. “How many more” compares.'] } },
  { id: 'da-4', skill: 'data', level: 2,
    text: 'The table shows the favourite drinks of some pupils.\nWhich drink is the most popular?',
    visual: { kind: 'table', head: ['Drink', 'Pupils'], rows: [['Milo', 14], ['Teh tarik', 9], ['Sirap', 11]] },
    options: ['Teh tarik', 'Sirap', 'Milo', 'All the same'], answer: 'Milo', vocab: ['most popular'],
    hints: ['Most popular means chosen by the most pupils.', 'Look at the Pupils column. Which number is biggest?', 'Compare 14, 9 and 11.'],
    show: ['Milo 14, Teh tarik 9, Sirap 11.', '14 is the biggest → Milo.'],
    bm: 'Jadual menunjukkan minuman kegemaran beberapa orang murid. Minuman manakah yang paling digemari?', simple: 'Which drink did the most pupils choose?',
    wrong: { 'Teh tarik': ['UNDERSTAND', 'Teh tarik has the fewest. Most popular has the most.'] } },
  { id: 'da-5', skill: 'data', level: 3,
    text: 'Look at the table again.\nHow many pupils were asked altogether?',
    visual: { kind: 'table', head: ['Drink', 'Pupils'], rows: [['Milo', 14], ['Teh tarik', 9], ['Sirap', 11]] },
    options: ['23', '34', '25', '14'], answer: '34', vocab: ['altogether'],
    hints: ['“Altogether” means all the groups together.', 'Add all the numbers in the Pupils column.', '14 + 9 + 11: try 9 + 11 first.'],
    show: ['9 + 11 = 20.', '20 + 14 = 34 pupils.'],
    bm: 'Lihat jadual sekali lagi. Berapakah jumlah keseluruhan murid yang ditanya?', simple: 'Add all the pupils in the table.',
    wrong: { '23': ['EXECUTE', 'Did you add all three drinks?'], '14': ['UNDERSTAND', 'That is only Milo. Add all the drinks.'] } },

  /* ───────── Multi-step (Mini Boss) ───────── */
  { id: 'wp-1', skill: 'word-problems', level: 4, related: ['money', 'times-divide'],
    text: 'Kak Ros buys 2 shirts at RM15.50 each.\nShe pays with RM50.00.\nHow much change does she get?',
    options: ['RM34.50', 'RM19.00', 'RM31.00', 'RM29.00'], answer: 'RM19.00', vocab: ['buys', 'each', 'pays', 'change'],
    hints: ['WHAT? We need the change. What must we know first?', 'HOW? Step 1: find the cost of 2 shirts. Step 2: take it from RM50.00.', 'DO: 2 × RM15.50 = RM31.00. Now find the change from RM50.00.'],
    show: ['Step 1: 2 × RM15.50 = RM31.00.', 'Step 2: RM50.00 − RM31.00 = RM19.00.'],
    bm: 'Kak Ros membeli 2 helai baju dengan harga RM15.50 sehelai. Dia membayar dengan RM50.00. Berapakah baki wang yang dia terima?', simple: 'One shirt is RM15.50. Kak Ros takes 2 shirts. She gives RM50.00. How much money comes back?',
    wrong: { 'RM34.50': ['PLAN', 'You took away only one shirt. She buys 2.'], 'RM31.00': ['UNDERSTAND', 'That is the cost of the shirts. The question asks for the change.'], 'RM29.00': ['EXECUTE', 'Check RM50.00 − RM31.00.'] },
    check: 'Check: RM31.00 + RM19.00 = RM50.00 ✓' },
  { id: 'wp-2', skill: 'word-problems', level: 4, related: ['duration', 'time24'],
    text: 'A train leaves Ipoh at 0950 hours.\nThe journey takes 2 hours 25 minutes.\nWhat time does it arrive in Kuala Lumpur?',
    options: ['1175 hours', '1215 hours', '1115 hours', '1225 hours'], answer: '1215 hours', vocab: ['leaves', 'journey', 'takes', 'arrive'],
    hints: ['WHAT? Are we finding the duration or the arrival time?', 'HOW? Add the hours first, then the minutes. Remember 60 minutes make 1 hour.', 'DO: 0950 + 2 hours = 1150. Now add 25 minutes: 1150 → 1200 is 10 minutes.'],
    show: ['0950 + 2 hours = 1150.', '1150 + 10 minutes = 1200, then + 15 minutes = 1215.', 'The train arrives at 1215 hours.'],
    bm: 'Sebuah kereta api bertolak dari Ipoh pada jam 0950. Perjalanan itu mengambil masa 2 jam 25 minit. Pukul berapakah kereta api itu tiba di Kuala Lumpur?', simple: 'The train goes at 0950 hours. The trip is 2 hours 25 minutes. When does it get to Kuala Lumpur?',
    wrong: { '1175 hours': ['CONCEPT', 'Minutes only go up to 59. 75 minutes is 1 hour 15 minutes.'], '1115 hours': ['EXECUTE', 'Check the hours you added.'] },
    check: 'Check: the minutes part is less than 60 ✓' },
  { id: 'wp-3', skill: 'word-problems', level: 4, related: ['perimeter', 'times-divide'],
    text: 'A garden is 8 m long and 5 m wide.\nFencing costs RM3 for each metre.\nHow much does it cost to fence around the whole garden?',
    visual: { kind: 'rect', w: 8, h: 5, unit: 'm' },
    options: ['RM120', 'RM39', 'RM78', 'RM26'], answer: 'RM78', vocab: ['wide', 'costs', 'each', 'around'],
    hints: ['WHAT? We need a cost. What must we measure first?', 'HOW? Step 1: find the perimeter. Step 2: multiply by RM3.', 'DO: 8 + 5 + 8 + 5 = 26 m. Now find the cost of 26 m.'],
    show: ['Perimeter: 8 + 5 + 8 + 5 = 26 m.', 'Cost: 26 × RM3 = RM78.'],
    bm: 'Sebuah kebun panjangnya 8 m dan lebarnya 5 m. Pagar berharga RM3 bagi setiap meter. Berapakah kos untuk memagar sekeliling kebun itu?', simple: 'The garden is 8 m by 5 m. One metre of fence is RM3. The fence goes all around. How much money?',
    wrong: { 'RM120': ['PLAN', 'You used the area. A fence goes around the edge.'], 'RM26': ['UNDERSTAND', '26 m is the length of fence. Now find the cost.'], 'RM39': ['EXECUTE', 'Check: did you go all the way around?'] },
    check: 'Check: 26 m × RM3 — the answer is money ✓' },
  { id: 'wp-4', skill: 'word-problems', level: 4, related: ['fractions', 'add-sub'],
    text: 'Amir has 36 marbles.\nHe gives 1/4 of them to his brother.\nHow many marbles does Amir have left?',
    options: ['9', '27', '32', '45'], answer: '27', vocab: ['gives', 'of', 'left'],
    hints: ['WHAT? We need the marbles Amir still has.', 'HOW? Step 1: find 1/4 of 36. Step 2: take that away from 36.', 'DO: 36 ÷ 4 = 9 marbles given away. Now find how many are left.'],
    show: ['1/4 of 36 = 36 ÷ 4 = 9.', '36 − 9 = 27 marbles left.'],
    bm: 'Amir ada 36 biji guli. Dia memberi 1/4 daripadanya kepada adiknya. Berapakah baki guli Amir?', simple: 'Amir has 36 marbles. He gives one quarter away. How many does he still have?',
    wrong: { '9': ['UNDERSTAND', '9 is what he gave away. The question asks what is left.'], '32': ['CONCEPT', '1/4 of 36 is not 4. Share 36 into 4 groups.'] },
    check: 'Check: 27 + 9 = 36 ✓' },
  { id: 'wp-5', skill: 'word-problems', level: 4, related: ['money', 'decimals'],
    text: 'Uncle Kamal saves RM8 every week.\nAfter 6 weeks, he spends RM19.50 on a gift.\nHow much money does he have now?',
    options: ['RM29.50', 'RM28.50', 'RM67.50', 'RM48.00'], answer: 'RM28.50', vocab: ['saves', 'spends'],
    hints: ['WHAT? Money at the end. What happens first, and what happens next?', 'HOW? Step 1: total saved in 6 weeks. Step 2: take away the gift.', 'DO: 6 × RM8 = RM48. Now RM48.00 − RM19.50.'],
    show: ['Saved: 6 × RM8 = RM48.00.', 'RM48.00 − RM19.50 = RM28.50.'],
    bm: 'Pak Cik Kamal menyimpan RM8 setiap minggu. Selepas 6 minggu, dia membelanjakan RM19.50 untuk sebuah hadiah. Berapakah wang yang dia ada sekarang?', simple: 'Uncle Kamal keeps RM8 each week for 6 weeks. Then he uses RM19.50 for a gift. How much is still with him?',
    wrong: { 'RM67.50': ['UNDERSTAND', 'Spending makes the money smaller.'], 'RM48.00': ['UNDERSTAND', 'That is the money saved. He spends some after that.'], 'RM29.50': ['EXECUTE', 'Check RM48.00 − RM19.50 again.'] },
    check: 'Check: RM28.50 + RM19.50 = RM48.00 ✓' }
];

/* Confusion ladders per skill — used by 😕 I'm Confused when a question has no ladder of its own.
   Each ladder steps back to a smaller idea using different numbers, so it never gives away the answer. */
FMQ.ladders = {
  'place-value': { intro: 'Let’s look at places first.', steps: [
    { text: 'In 352, which digit is in the tens place?', options: ['5', '3', '2'], answer: '5', hint: 'From the right: ones, then tens.' },
    { text: 'So the 5 in 352 is worth…', options: ['50', '5', '500'], answer: '50', hint: '5 tens = 50.' } ] },
  'add-sub': { intro: 'Let’s decide: join or compare?', steps: [
    { text: 'Ali has 9 apples. He eats 4. Does he have more or fewer now?', options: ['Fewer', 'More'], answer: 'Fewer', hint: 'Eating makes the apples go away.' },
    { text: 'Which operation makes an amount smaller?', options: ['Subtract (−)', 'Add (+)'], answer: 'Subtract (−)', hint: 'Taking away.' } ] },
  'times-divide': { intro: 'Let’s think in equal groups.', steps: [
    { text: '3 plates, 4 kuih on each plate. How many kuih?', visual: { kind: 'dots', total: 12, groups: 3 }, options: ['12', '7', '1'], answer: '12', hint: '4 + 4 + 4.' },
    { text: '12 kuih shared equally on 3 plates. How many on each plate?', options: ['4', '9', '36'], answer: '4', hint: 'Share them one by one onto the plates.' } ] },
  'decimals': { intro: 'Let’s line up the decimal point.', steps: [
    { text: 'Which is the same as 4.5?', options: ['4.50', '4.05', '45'], answer: '4.50', hint: 'A zero at the end of a decimal does not change it.' },
    { text: 'What is 4.50 − 1.00?', options: ['3.50', '5.50', '3.05'], answer: '3.50', hint: 'Only the ones change.' } ] },
  'money': { intro: 'Let’s think about what happens to the money.', steps: [
    { text: 'You have RM10. You buy a book. Do you have more or less money?', options: ['Less', 'More'], answer: 'Less', hint: 'Paying uses up money.' },
    { text: 'What is RM10.00 − RM4.00?', options: ['RM6.00', 'RM14.00', 'RM4.00'], answer: 'RM6.00', hint: 'Take 4 away from 10.' },
    { text: 'What is RM10.00 − RM4.50?', options: ['RM5.50', 'RM6.50', 'RM14.50'], answer: 'RM5.50', hint: 'Take away RM4, then 50 sen more.' } ] },
  'fractions': { intro: 'Let’s look at equal parts.', steps: [
    { text: 'A cake is cut into 3 equal parts. One part is…', visual: { kind: 'bar', parts: 3, shaded: 1 }, options: ['1/3', '3/1', '1/2'], answer: '1/3', hint: '1 part out of 3 equal parts.' },
    { text: '1/3 of 9 sweets is…', visual: { kind: 'dots', total: 9, groups: 3 }, options: ['3', '6', '27'], answer: '3', hint: 'Share 9 into 3 equal groups.' } ] },
  'percent': { intro: 'Let’s start with “out of 100”.', steps: [
    { text: 'Percent means…', options: ['out of 100', 'out of 10', 'times 100'], answer: 'out of 100', hint: '“Cent” is like 100, as in “century”.' },
    { text: '4/10 = ?/100', options: ['40/100', '4/100', '14/100'], answer: '40/100', hint: 'Multiply top and bottom by 10.' } ] },
  'time24': { intro: 'Let’s look at the 24-hour clock.', steps: [
    { text: '12 noon in 24-hour time is…', options: ['1200 hours', '0000 hours', '2400 hours'], answer: '1200 hours', hint: 'Noon is 12.' },
    { text: '2:00 p.m. is…', options: ['1400 hours', '0200 hours', '1200 hours'], answer: '1400 hours', hint: '2 + 12 = 14.' } ] },
  'duration': { intro: 'Let’s count time in small jumps.', steps: [
    { text: 'From 1:00 p.m. to 2:00 p.m. is…', options: ['1 hour', '100 minutes', '2 hours'], answer: '1 hour', hint: 'The hour goes up by one.' },
    { text: '1 hour is how many minutes?', options: ['60', '100', '30'], answer: '60', hint: 'Think of the clock face.' } ] },
  'measure': { intro: 'Let’s make the units the same.', steps: [
    { text: '1 kg = ? g', options: ['1 000 g', '100 g', '10 g'], answer: '1 000 g', hint: '“Kilo” means 1 000.' },
    { text: '1 litre = ? ml', options: ['1 000 ml', '100 ml', '10 ml'], answer: '1 000 ml', hint: '“Milli” means one thousandth.' } ] },
  'perimeter': { intro: 'Let’s walk around a shape.', steps: [
    { text: 'Perimeter is…', options: ['the distance around the edge', 'the space inside', 'the longest side'], answer: 'the distance around the edge', hint: 'Imagine an ant walking all the way round.' },
    { text: 'A triangle has sides 3 cm, 4 cm and 5 cm. Its perimeter is…', options: ['12 cm', '60 cm', '7 cm'], answer: '12 cm', hint: 'Add all three sides.' } ] },
  'area': { intro: 'Let’s count squares.', steps: [
    { text: 'How many squares?', visual: { kind: 'grid', cols: 3, rows: 2 }, options: ['6', '5', '10'], answer: '6', hint: '2 rows of 3.' },
    { text: '2 rows of 3 squares is the same as…', options: ['2 × 3', '2 + 3', '3 − 2'], answer: '2 × 3', hint: 'Rows of equal squares → multiply.' } ] },
  'ratio': { intro: 'Let’s compare two groups.', steps: [
    { text: '2 cats and 5 dogs. The ratio of cats to dogs is…', options: ['2 : 5', '5 : 2', '2 : 7'], answer: '2 : 5', hint: 'Cats first, then dogs.' },
    { text: '1 bicycle has 2 wheels. 4 bicycles have…', options: ['8 wheels', '6 wheels', '2 wheels'], answer: '8 wheels', hint: '4 × 2.' } ] },
  'data': { intro: 'Let’s read the key first.', steps: [
    { text: 'Key: ★ = 2 stars. How many is ★★★?', options: ['6', '3', '5'], answer: '6', hint: 'Each ★ is worth 2.' },
    { text: 'In a table, the biggest number shows…', options: ['the most', 'the least', 'the middle'], answer: 'the most', hint: 'Bigger number, more things.' } ] },
  'word-problems': { intro: 'Let’s break it into steps.', steps: [
    { text: 'A long question often has…', options: ['more than one step', 'only one number', 'no answer'], answer: 'more than one step', hint: 'Look for “first” and “then”.' },
    { text: 'Which should you find first: what you KNOW or what you NEED?', options: ['What I need to find', 'The biggest number'], answer: 'What I need to find', hint: 'WHAT is the question asking?' } ] }
};

FMQ.question = function (id) {
  return FMQ.questions.find(function (q) { return q.id === id; });
};
